// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module gemm (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        insn_raw_V,
        uop_mem_V_2_address0,
        uop_mem_V_2_ce0,
        uop_mem_V_2_q0,
        acc_mem_V_2_address0,
        acc_mem_V_2_ce0,
        acc_mem_V_2_we0,
        acc_mem_V_2_d0,
        acc_mem_V_2_q0,
        inp_mem_V_Addr_A,
        inp_mem_V_EN_A,
        inp_mem_V_WEN_A,
        inp_mem_V_Din_A,
        inp_mem_V_Dout_A,
        wgt_mem_0_V_Addr_A,
        wgt_mem_0_V_EN_A,
        wgt_mem_0_V_WEN_A,
        wgt_mem_0_V_Din_A,
        wgt_mem_0_V_Dout_A,
        wgt_mem_1_V_Addr_A,
        wgt_mem_1_V_EN_A,
        wgt_mem_1_V_WEN_A,
        wgt_mem_1_V_Din_A,
        wgt_mem_1_V_Dout_A,
        out_mem_V_Addr_A,
        out_mem_V_EN_A,
        out_mem_V_WEN_A,
        out_mem_V_Din_A,
        out_mem_V_Dout_A
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_pp0_stage0 = 10'd8;
parameter    ap_ST_fsm_pp0_stage1 = 10'd16;
parameter    ap_ST_fsm_pp0_stage2 = 10'd32;
parameter    ap_ST_fsm_pp0_stage3 = 10'd64;
parameter    ap_ST_fsm_pp0_stage4 = 10'd128;
parameter    ap_ST_fsm_pp0_stage5 = 10'd256;
parameter    ap_ST_fsm_state11 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [127:0] insn_raw_V;
output  [12:0] uop_mem_V_2_address0;
output   uop_mem_V_2_ce0;
input  [31:0] uop_mem_V_2_q0;
output  [10:0] acc_mem_V_2_address0;
output   acc_mem_V_2_ce0;
output  [63:0] acc_mem_V_2_we0;
output  [511:0] acc_mem_V_2_d0;
input  [511:0] acc_mem_V_2_q0;
output  [31:0] inp_mem_V_Addr_A;
output   inp_mem_V_EN_A;
output  [15:0] inp_mem_V_WEN_A;
output  [127:0] inp_mem_V_Din_A;
input  [127:0] inp_mem_V_Dout_A;
output  [31:0] wgt_mem_0_V_Addr_A;
output   wgt_mem_0_V_EN_A;
output  [127:0] wgt_mem_0_V_WEN_A;
output  [1023:0] wgt_mem_0_V_Din_A;
input  [1023:0] wgt_mem_0_V_Dout_A;
output  [31:0] wgt_mem_1_V_Addr_A;
output   wgt_mem_1_V_EN_A;
output  [127:0] wgt_mem_1_V_WEN_A;
output  [1023:0] wgt_mem_1_V_Din_A;
input  [1023:0] wgt_mem_1_V_Dout_A;
output  [31:0] out_mem_V_Addr_A;
output   out_mem_V_EN_A;
output  [15:0] out_mem_V_WEN_A;
output  [127:0] out_mem_V_Din_A;
input  [127:0] out_mem_V_Dout_A;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg uop_mem_V_2_ce0;
reg[10:0] acc_mem_V_2_address0;
reg acc_mem_V_2_ce0;
reg[63:0] acc_mem_V_2_we0;
reg inp_mem_V_EN_A;
reg wgt_mem_0_V_EN_A;
reg wgt_mem_1_V_EN_A;
reg out_mem_V_EN_A;
reg[15:0] out_mem_V_WEN_A;

(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg  signed [31:0] upc_0_reg_811;
reg   [0:0] gemm_reset_reg_4748;
reg   [13:0] inst_iter_out_reg;
wire   [13:0] it_out_fu_1137_p2;
reg   [13:0] it_out_reg_4761;
wire    ap_CS_fsm_state2;
reg   [13:0] inst_iter_in_reg;
wire   [0:0] icmp_iter_out;
wire   [0:0] icmp_iter_in;
wire    ap_CS_fsm_state3;
wire   [13:0] it_in_fu_1157_p2;
reg   [13:0] it_in_reg_4775;
wire   [31:0] upc_fu_1172_p1;
wire   [31:0] zext_ln35_fu_1185_p1;
reg   [31:0] zext_ln35_reg_4785;
wire   [11:0] dst_offset_out_V_fu_1202_p2;
wire   [11:0] src_offset_out_V_fu_1221_p2;
wire   [10:0] wgt_offset_out_V_fu_1240_p2;
wire   [0:0] icmp_ln35_fu_1246_p2;
reg   [0:0] icmp_ln35_reg_4805;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_CS_fsm_pp0_stage1;
wire   [63:0] zext_ln544_2_fu_1321_p1;
reg   [63:0] zext_ln544_2_reg_4829;
reg   [10:0] acc_mem_V_1_addr_reg_4834;
wire    ap_CS_fsm_pp0_stage2;
wire   [31:0] upc_1_fu_4470_p2;
reg   [31:0] upc_1_reg_6279;
wire    ap_CS_fsm_pp0_stage5;
reg    ap_enable_reg_pp0_iter0;
wire   [11:0] dst_offset_in_V_1_fu_4691_p2;
wire    ap_CS_fsm_state11;
wire   [11:0] src_offset_in_V_1_fu_4710_p2;
wire   [10:0] wgt_offset_in_V_1_fu_4729_p2;
reg    ap_condition_pp0_exit_iter0_state4;
reg    ap_enable_reg_pp0_iter1;
wire   [7:0] grp_gemm_core_fu_821_i_tensor_0_0_V_rea;
wire   [7:0] grp_gemm_core_fu_821_i_tensor_0_1_V_rea;
wire   [7:0] grp_gemm_core_fu_821_i_tensor_0_2_V_rea;
wire   [7:0] grp_gemm_core_fu_821_i_tensor_0_3_V_rea;
wire   [7:0] grp_gemm_core_fu_821_i_tensor_0_4_V_rea;
wire   [7:0] grp_gemm_core_fu_821_i_tensor_0_5_V_rea;
wire   [7:0] grp_gemm_core_fu_821_i_tensor_0_6_V_rea;
wire   [7:0] grp_gemm_core_fu_821_i_tensor_0_7_V_rea;
wire   [7:0] grp_gemm_core_fu_821_i_tensor_0_8_V_rea;
wire   [7:0] grp_gemm_core_fu_821_i_tensor_0_9_V_rea;
wire   [7:0] grp_gemm_core_fu_821_i_tensor_0_10_V_re;
wire   [7:0] grp_gemm_core_fu_821_i_tensor_0_11_V_re;
wire   [7:0] grp_gemm_core_fu_821_i_tensor_0_12_V_re;
wire   [7:0] grp_gemm_core_fu_821_i_tensor_0_13_V_re;
wire   [7:0] grp_gemm_core_fu_821_i_tensor_0_14_V_re;
wire   [7:0] grp_gemm_core_fu_821_i_tensor_0_15_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_0_0_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_0_1_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_0_2_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_0_3_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_0_4_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_0_5_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_0_6_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_0_7_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_0_8_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_0_9_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_0_10_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_0_11_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_0_12_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_0_13_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_0_14_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_0_15_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_1_0_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_1_1_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_1_2_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_1_3_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_1_4_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_1_5_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_1_6_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_1_7_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_1_8_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_1_9_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_1_10_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_1_11_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_1_12_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_1_13_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_1_14_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_1_15_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_2_0_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_2_1_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_2_2_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_2_3_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_2_4_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_2_5_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_2_6_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_2_7_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_2_8_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_2_9_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_2_10_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_2_11_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_2_12_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_2_13_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_2_14_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_2_15_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_3_0_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_3_1_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_3_2_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_3_3_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_3_4_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_3_5_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_3_6_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_3_7_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_3_8_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_3_9_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_3_10_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_3_11_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_3_12_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_3_13_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_3_14_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_3_15_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_4_0_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_4_1_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_4_2_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_4_3_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_4_4_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_4_5_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_4_6_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_4_7_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_4_8_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_4_9_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_4_10_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_4_11_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_4_12_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_4_13_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_4_14_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_4_15_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_5_0_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_5_1_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_5_2_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_5_3_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_5_4_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_5_5_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_5_6_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_5_7_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_5_8_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_5_9_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_5_10_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_5_11_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_5_12_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_5_13_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_5_14_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_5_15_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_6_0_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_6_1_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_6_2_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_6_3_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_6_4_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_6_5_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_6_6_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_6_7_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_6_8_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_6_9_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_6_10_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_6_11_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_6_12_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_6_13_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_6_14_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_6_15_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_7_0_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_7_1_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_7_2_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_7_3_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_7_4_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_7_5_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_7_6_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_7_7_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_7_8_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_7_9_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_7_10_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_7_11_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_7_12_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_7_13_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_7_14_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_7_15_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_8_0_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_8_1_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_8_2_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_8_3_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_8_4_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_8_5_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_8_6_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_8_7_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_8_8_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_8_9_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_8_10_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_8_11_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_8_12_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_8_13_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_8_14_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_8_15_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_9_0_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_9_1_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_9_2_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_9_3_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_9_4_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_9_5_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_9_6_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_9_7_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_9_8_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_9_9_V_rea;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_9_10_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_9_11_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_9_12_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_9_13_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_9_14_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_9_15_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_10_0_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_10_1_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_10_2_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_10_3_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_10_4_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_10_5_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_10_6_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_10_7_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_10_8_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_10_9_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_10_10_V_r;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_10_11_V_r;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_10_12_V_r;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_10_13_V_r;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_10_14_V_r;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_10_15_V_r;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_11_0_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_11_1_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_11_2_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_11_3_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_11_4_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_11_5_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_11_6_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_11_7_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_11_8_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_11_9_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_11_10_V_r;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_11_11_V_r;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_11_12_V_r;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_11_13_V_r;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_11_14_V_r;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_11_15_V_r;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_12_0_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_12_1_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_12_2_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_12_3_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_12_4_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_12_5_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_12_6_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_12_7_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_12_8_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_12_9_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_12_10_V_r;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_12_11_V_r;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_12_12_V_r;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_12_13_V_r;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_12_14_V_r;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_12_15_V_r;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_13_0_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_13_1_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_13_2_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_13_3_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_13_4_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_13_5_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_13_6_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_13_7_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_13_8_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_13_9_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_13_10_V_r;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_13_11_V_r;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_13_12_V_r;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_13_13_V_r;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_13_14_V_r;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_13_15_V_r;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_14_0_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_14_1_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_14_2_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_14_3_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_14_4_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_14_5_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_14_6_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_14_7_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_14_8_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_14_9_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_14_10_V_r;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_14_11_V_r;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_14_12_V_r;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_14_13_V_r;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_14_14_V_r;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_14_15_V_r;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_15_0_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_15_1_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_15_2_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_15_3_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_15_4_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_15_5_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_15_6_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_15_7_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_15_8_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_15_9_V_re;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_15_10_V_r;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_15_11_V_r;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_15_12_V_r;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_15_13_V_r;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_15_14_V_r;
wire   [7:0] grp_gemm_core_fu_821_w_tensor_15_15_V_r;
wire   [31:0] grp_gemm_core_fu_821_a_tensor_0_0_V_rea;
wire   [31:0] grp_gemm_core_fu_821_a_tensor_0_1_V_rea;
wire   [31:0] grp_gemm_core_fu_821_a_tensor_0_2_V_rea;
wire   [31:0] grp_gemm_core_fu_821_a_tensor_0_3_V_rea;
wire   [31:0] grp_gemm_core_fu_821_a_tensor_0_4_V_rea;
wire   [31:0] grp_gemm_core_fu_821_a_tensor_0_5_V_rea;
wire   [31:0] grp_gemm_core_fu_821_a_tensor_0_6_V_rea;
wire   [31:0] grp_gemm_core_fu_821_a_tensor_0_7_V_rea;
wire   [31:0] grp_gemm_core_fu_821_a_tensor_0_8_V_rea;
wire   [31:0] grp_gemm_core_fu_821_a_tensor_0_9_V_rea;
wire   [31:0] grp_gemm_core_fu_821_a_tensor_0_10_V_re;
wire   [31:0] grp_gemm_core_fu_821_a_tensor_0_11_V_re;
wire   [31:0] grp_gemm_core_fu_821_a_tensor_0_12_V_re;
wire   [31:0] grp_gemm_core_fu_821_a_tensor_0_13_V_re;
wire   [31:0] grp_gemm_core_fu_821_a_tensor_0_14_V_re;
wire   [31:0] grp_gemm_core_fu_821_a_tensor_0_15_V_re;
wire    grp_gemm_core_fu_821_gemm_reset;
wire   [31:0] grp_gemm_core_fu_821_ap_return_0;
wire   [31:0] grp_gemm_core_fu_821_ap_return_1;
wire   [31:0] grp_gemm_core_fu_821_ap_return_2;
wire   [31:0] grp_gemm_core_fu_821_ap_return_3;
wire   [31:0] grp_gemm_core_fu_821_ap_return_4;
wire   [31:0] grp_gemm_core_fu_821_ap_return_5;
wire   [31:0] grp_gemm_core_fu_821_ap_return_6;
wire   [31:0] grp_gemm_core_fu_821_ap_return_7;
wire   [31:0] grp_gemm_core_fu_821_ap_return_8;
wire   [31:0] grp_gemm_core_fu_821_ap_return_9;
wire   [31:0] grp_gemm_core_fu_821_ap_return_10;
wire   [31:0] grp_gemm_core_fu_821_ap_return_11;
wire   [31:0] grp_gemm_core_fu_821_ap_return_12;
wire   [31:0] grp_gemm_core_fu_821_ap_return_13;
wire   [31:0] grp_gemm_core_fu_821_ap_return_14;
wire   [31:0] grp_gemm_core_fu_821_ap_return_15;
wire   [7:0] grp_gemm_core_fu_821_ap_return_16;
wire   [7:0] grp_gemm_core_fu_821_ap_return_17;
wire   [7:0] grp_gemm_core_fu_821_ap_return_18;
wire   [7:0] grp_gemm_core_fu_821_ap_return_19;
wire   [7:0] grp_gemm_core_fu_821_ap_return_20;
wire   [7:0] grp_gemm_core_fu_821_ap_return_21;
wire   [7:0] grp_gemm_core_fu_821_ap_return_22;
wire   [7:0] grp_gemm_core_fu_821_ap_return_23;
wire   [7:0] grp_gemm_core_fu_821_ap_return_24;
wire   [7:0] grp_gemm_core_fu_821_ap_return_25;
wire   [7:0] grp_gemm_core_fu_821_ap_return_26;
wire   [7:0] grp_gemm_core_fu_821_ap_return_27;
wire   [7:0] grp_gemm_core_fu_821_ap_return_28;
wire   [7:0] grp_gemm_core_fu_821_ap_return_29;
wire   [7:0] grp_gemm_core_fu_821_ap_return_30;
wire   [7:0] grp_gemm_core_fu_821_ap_return_31;
reg   [11:0] dst_offset_in_V_reg_720;
reg   [11:0] src_offset_in_V_reg_732;
reg   [10:0] wgt_offset_in_V_reg_744;
reg   [13:0] iter_out_reg;
reg   [11:0] dst_offset_in_0_reg_767;
reg   [11:0] src_offset_in_0_reg_778;
reg   [10:0] wgt_offset_in_0_reg_789;
reg   [13:0] iter_in_reg;
reg  signed [31:0] ap_phi_mux_upc_0_phi_fu_814_p4;
wire  signed [63:0] sext_ln35_fu_1251_p1;
wire   [63:0] zext_ln544_fu_1310_p1;
wire   [63:0] zext_ln544_1_fu_1316_p1;
wire   [31:0] wgt_mem_0_V_Addr_A_orig;
wire   [31:0] wgt_mem_1_V_Addr_A_orig;
wire   [31:0] inp_mem_V_Addr_A_orig;
wire   [31:0] out_mem_V_Addr_A_orig;
wire   [12:0] p_Result_4_fu_1163_p4;
wire   [13:0] p_Result_8_fu_1176_p4;
wire   [10:0] p_Result_s_fu_1189_p4;
wire   [11:0] zext_ln700_fu_1198_p1;
wire   [10:0] p_Result_1_fu_1208_p4;
wire   [11:0] zext_ln700_1_fu_1217_p1;
wire   [9:0] p_Result_5_fu_1227_p4;
wire   [10:0] zext_ln700_2_fu_1236_p1;
wire   [10:0] trunc_ln647_fu_1256_p1;
wire   [11:0] zext_ln209_fu_1260_p1;
wire   [10:0] p_Result_7_fu_1270_p4;
wire   [11:0] zext_ln209_1_fu_1280_p1;
wire   [9:0] p_Result_9_fu_1290_p4;
wire   [10:0] zext_ln209_2_fu_1300_p1;
wire   [10:0] wgt_idx_V_fu_1304_p2;
wire   [11:0] src_idx_V_fu_1284_p2;
wire   [11:0] dst_idx_V_fu_1264_p2;
wire   [10:0] p_Result_6_fu_4678_p4;
wire   [11:0] zext_ln700_3_fu_4687_p1;
wire   [10:0] p_Result_10_fu_4697_p4;
wire   [11:0] zext_ln700_4_fu_4706_p1;
wire   [9:0] p_Result_11_fu_4716_p4;
wire   [10:0] zext_ln700_5_fu_4725_p1;
reg   [9:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 10'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

gemm_core grp_gemm_core_fu_821(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .i_tensor_0_0_V_rea(grp_gemm_core_fu_821_i_tensor_0_0_V_rea),
    .i_tensor_0_1_V_rea(grp_gemm_core_fu_821_i_tensor_0_1_V_rea),
    .i_tensor_0_2_V_rea(grp_gemm_core_fu_821_i_tensor_0_2_V_rea),
    .i_tensor_0_3_V_rea(grp_gemm_core_fu_821_i_tensor_0_3_V_rea),
    .i_tensor_0_4_V_rea(grp_gemm_core_fu_821_i_tensor_0_4_V_rea),
    .i_tensor_0_5_V_rea(grp_gemm_core_fu_821_i_tensor_0_5_V_rea),
    .i_tensor_0_6_V_rea(grp_gemm_core_fu_821_i_tensor_0_6_V_rea),
    .i_tensor_0_7_V_rea(grp_gemm_core_fu_821_i_tensor_0_7_V_rea),
    .i_tensor_0_8_V_rea(grp_gemm_core_fu_821_i_tensor_0_8_V_rea),
    .i_tensor_0_9_V_rea(grp_gemm_core_fu_821_i_tensor_0_9_V_rea),
    .i_tensor_0_10_V_re(grp_gemm_core_fu_821_i_tensor_0_10_V_re),
    .i_tensor_0_11_V_re(grp_gemm_core_fu_821_i_tensor_0_11_V_re),
    .i_tensor_0_12_V_re(grp_gemm_core_fu_821_i_tensor_0_12_V_re),
    .i_tensor_0_13_V_re(grp_gemm_core_fu_821_i_tensor_0_13_V_re),
    .i_tensor_0_14_V_re(grp_gemm_core_fu_821_i_tensor_0_14_V_re),
    .i_tensor_0_15_V_re(grp_gemm_core_fu_821_i_tensor_0_15_V_re),
    .w_tensor_0_0_V_rea(grp_gemm_core_fu_821_w_tensor_0_0_V_rea),
    .w_tensor_0_1_V_rea(grp_gemm_core_fu_821_w_tensor_0_1_V_rea),
    .w_tensor_0_2_V_rea(grp_gemm_core_fu_821_w_tensor_0_2_V_rea),
    .w_tensor_0_3_V_rea(grp_gemm_core_fu_821_w_tensor_0_3_V_rea),
    .w_tensor_0_4_V_rea(grp_gemm_core_fu_821_w_tensor_0_4_V_rea),
    .w_tensor_0_5_V_rea(grp_gemm_core_fu_821_w_tensor_0_5_V_rea),
    .w_tensor_0_6_V_rea(grp_gemm_core_fu_821_w_tensor_0_6_V_rea),
    .w_tensor_0_7_V_rea(grp_gemm_core_fu_821_w_tensor_0_7_V_rea),
    .w_tensor_0_8_V_rea(grp_gemm_core_fu_821_w_tensor_0_8_V_rea),
    .w_tensor_0_9_V_rea(grp_gemm_core_fu_821_w_tensor_0_9_V_rea),
    .w_tensor_0_10_V_re(grp_gemm_core_fu_821_w_tensor_0_10_V_re),
    .w_tensor_0_11_V_re(grp_gemm_core_fu_821_w_tensor_0_11_V_re),
    .w_tensor_0_12_V_re(grp_gemm_core_fu_821_w_tensor_0_12_V_re),
    .w_tensor_0_13_V_re(grp_gemm_core_fu_821_w_tensor_0_13_V_re),
    .w_tensor_0_14_V_re(grp_gemm_core_fu_821_w_tensor_0_14_V_re),
    .w_tensor_0_15_V_re(grp_gemm_core_fu_821_w_tensor_0_15_V_re),
    .w_tensor_1_0_V_rea(grp_gemm_core_fu_821_w_tensor_1_0_V_rea),
    .w_tensor_1_1_V_rea(grp_gemm_core_fu_821_w_tensor_1_1_V_rea),
    .w_tensor_1_2_V_rea(grp_gemm_core_fu_821_w_tensor_1_2_V_rea),
    .w_tensor_1_3_V_rea(grp_gemm_core_fu_821_w_tensor_1_3_V_rea),
    .w_tensor_1_4_V_rea(grp_gemm_core_fu_821_w_tensor_1_4_V_rea),
    .w_tensor_1_5_V_rea(grp_gemm_core_fu_821_w_tensor_1_5_V_rea),
    .w_tensor_1_6_V_rea(grp_gemm_core_fu_821_w_tensor_1_6_V_rea),
    .w_tensor_1_7_V_rea(grp_gemm_core_fu_821_w_tensor_1_7_V_rea),
    .w_tensor_1_8_V_rea(grp_gemm_core_fu_821_w_tensor_1_8_V_rea),
    .w_tensor_1_9_V_rea(grp_gemm_core_fu_821_w_tensor_1_9_V_rea),
    .w_tensor_1_10_V_re(grp_gemm_core_fu_821_w_tensor_1_10_V_re),
    .w_tensor_1_11_V_re(grp_gemm_core_fu_821_w_tensor_1_11_V_re),
    .w_tensor_1_12_V_re(grp_gemm_core_fu_821_w_tensor_1_12_V_re),
    .w_tensor_1_13_V_re(grp_gemm_core_fu_821_w_tensor_1_13_V_re),
    .w_tensor_1_14_V_re(grp_gemm_core_fu_821_w_tensor_1_14_V_re),
    .w_tensor_1_15_V_re(grp_gemm_core_fu_821_w_tensor_1_15_V_re),
    .w_tensor_2_0_V_rea(grp_gemm_core_fu_821_w_tensor_2_0_V_rea),
    .w_tensor_2_1_V_rea(grp_gemm_core_fu_821_w_tensor_2_1_V_rea),
    .w_tensor_2_2_V_rea(grp_gemm_core_fu_821_w_tensor_2_2_V_rea),
    .w_tensor_2_3_V_rea(grp_gemm_core_fu_821_w_tensor_2_3_V_rea),
    .w_tensor_2_4_V_rea(grp_gemm_core_fu_821_w_tensor_2_4_V_rea),
    .w_tensor_2_5_V_rea(grp_gemm_core_fu_821_w_tensor_2_5_V_rea),
    .w_tensor_2_6_V_rea(grp_gemm_core_fu_821_w_tensor_2_6_V_rea),
    .w_tensor_2_7_V_rea(grp_gemm_core_fu_821_w_tensor_2_7_V_rea),
    .w_tensor_2_8_V_rea(grp_gemm_core_fu_821_w_tensor_2_8_V_rea),
    .w_tensor_2_9_V_rea(grp_gemm_core_fu_821_w_tensor_2_9_V_rea),
    .w_tensor_2_10_V_re(grp_gemm_core_fu_821_w_tensor_2_10_V_re),
    .w_tensor_2_11_V_re(grp_gemm_core_fu_821_w_tensor_2_11_V_re),
    .w_tensor_2_12_V_re(grp_gemm_core_fu_821_w_tensor_2_12_V_re),
    .w_tensor_2_13_V_re(grp_gemm_core_fu_821_w_tensor_2_13_V_re),
    .w_tensor_2_14_V_re(grp_gemm_core_fu_821_w_tensor_2_14_V_re),
    .w_tensor_2_15_V_re(grp_gemm_core_fu_821_w_tensor_2_15_V_re),
    .w_tensor_3_0_V_rea(grp_gemm_core_fu_821_w_tensor_3_0_V_rea),
    .w_tensor_3_1_V_rea(grp_gemm_core_fu_821_w_tensor_3_1_V_rea),
    .w_tensor_3_2_V_rea(grp_gemm_core_fu_821_w_tensor_3_2_V_rea),
    .w_tensor_3_3_V_rea(grp_gemm_core_fu_821_w_tensor_3_3_V_rea),
    .w_tensor_3_4_V_rea(grp_gemm_core_fu_821_w_tensor_3_4_V_rea),
    .w_tensor_3_5_V_rea(grp_gemm_core_fu_821_w_tensor_3_5_V_rea),
    .w_tensor_3_6_V_rea(grp_gemm_core_fu_821_w_tensor_3_6_V_rea),
    .w_tensor_3_7_V_rea(grp_gemm_core_fu_821_w_tensor_3_7_V_rea),
    .w_tensor_3_8_V_rea(grp_gemm_core_fu_821_w_tensor_3_8_V_rea),
    .w_tensor_3_9_V_rea(grp_gemm_core_fu_821_w_tensor_3_9_V_rea),
    .w_tensor_3_10_V_re(grp_gemm_core_fu_821_w_tensor_3_10_V_re),
    .w_tensor_3_11_V_re(grp_gemm_core_fu_821_w_tensor_3_11_V_re),
    .w_tensor_3_12_V_re(grp_gemm_core_fu_821_w_tensor_3_12_V_re),
    .w_tensor_3_13_V_re(grp_gemm_core_fu_821_w_tensor_3_13_V_re),
    .w_tensor_3_14_V_re(grp_gemm_core_fu_821_w_tensor_3_14_V_re),
    .w_tensor_3_15_V_re(grp_gemm_core_fu_821_w_tensor_3_15_V_re),
    .w_tensor_4_0_V_rea(grp_gemm_core_fu_821_w_tensor_4_0_V_rea),
    .w_tensor_4_1_V_rea(grp_gemm_core_fu_821_w_tensor_4_1_V_rea),
    .w_tensor_4_2_V_rea(grp_gemm_core_fu_821_w_tensor_4_2_V_rea),
    .w_tensor_4_3_V_rea(grp_gemm_core_fu_821_w_tensor_4_3_V_rea),
    .w_tensor_4_4_V_rea(grp_gemm_core_fu_821_w_tensor_4_4_V_rea),
    .w_tensor_4_5_V_rea(grp_gemm_core_fu_821_w_tensor_4_5_V_rea),
    .w_tensor_4_6_V_rea(grp_gemm_core_fu_821_w_tensor_4_6_V_rea),
    .w_tensor_4_7_V_rea(grp_gemm_core_fu_821_w_tensor_4_7_V_rea),
    .w_tensor_4_8_V_rea(grp_gemm_core_fu_821_w_tensor_4_8_V_rea),
    .w_tensor_4_9_V_rea(grp_gemm_core_fu_821_w_tensor_4_9_V_rea),
    .w_tensor_4_10_V_re(grp_gemm_core_fu_821_w_tensor_4_10_V_re),
    .w_tensor_4_11_V_re(grp_gemm_core_fu_821_w_tensor_4_11_V_re),
    .w_tensor_4_12_V_re(grp_gemm_core_fu_821_w_tensor_4_12_V_re),
    .w_tensor_4_13_V_re(grp_gemm_core_fu_821_w_tensor_4_13_V_re),
    .w_tensor_4_14_V_re(grp_gemm_core_fu_821_w_tensor_4_14_V_re),
    .w_tensor_4_15_V_re(grp_gemm_core_fu_821_w_tensor_4_15_V_re),
    .w_tensor_5_0_V_rea(grp_gemm_core_fu_821_w_tensor_5_0_V_rea),
    .w_tensor_5_1_V_rea(grp_gemm_core_fu_821_w_tensor_5_1_V_rea),
    .w_tensor_5_2_V_rea(grp_gemm_core_fu_821_w_tensor_5_2_V_rea),
    .w_tensor_5_3_V_rea(grp_gemm_core_fu_821_w_tensor_5_3_V_rea),
    .w_tensor_5_4_V_rea(grp_gemm_core_fu_821_w_tensor_5_4_V_rea),
    .w_tensor_5_5_V_rea(grp_gemm_core_fu_821_w_tensor_5_5_V_rea),
    .w_tensor_5_6_V_rea(grp_gemm_core_fu_821_w_tensor_5_6_V_rea),
    .w_tensor_5_7_V_rea(grp_gemm_core_fu_821_w_tensor_5_7_V_rea),
    .w_tensor_5_8_V_rea(grp_gemm_core_fu_821_w_tensor_5_8_V_rea),
    .w_tensor_5_9_V_rea(grp_gemm_core_fu_821_w_tensor_5_9_V_rea),
    .w_tensor_5_10_V_re(grp_gemm_core_fu_821_w_tensor_5_10_V_re),
    .w_tensor_5_11_V_re(grp_gemm_core_fu_821_w_tensor_5_11_V_re),
    .w_tensor_5_12_V_re(grp_gemm_core_fu_821_w_tensor_5_12_V_re),
    .w_tensor_5_13_V_re(grp_gemm_core_fu_821_w_tensor_5_13_V_re),
    .w_tensor_5_14_V_re(grp_gemm_core_fu_821_w_tensor_5_14_V_re),
    .w_tensor_5_15_V_re(grp_gemm_core_fu_821_w_tensor_5_15_V_re),
    .w_tensor_6_0_V_rea(grp_gemm_core_fu_821_w_tensor_6_0_V_rea),
    .w_tensor_6_1_V_rea(grp_gemm_core_fu_821_w_tensor_6_1_V_rea),
    .w_tensor_6_2_V_rea(grp_gemm_core_fu_821_w_tensor_6_2_V_rea),
    .w_tensor_6_3_V_rea(grp_gemm_core_fu_821_w_tensor_6_3_V_rea),
    .w_tensor_6_4_V_rea(grp_gemm_core_fu_821_w_tensor_6_4_V_rea),
    .w_tensor_6_5_V_rea(grp_gemm_core_fu_821_w_tensor_6_5_V_rea),
    .w_tensor_6_6_V_rea(grp_gemm_core_fu_821_w_tensor_6_6_V_rea),
    .w_tensor_6_7_V_rea(grp_gemm_core_fu_821_w_tensor_6_7_V_rea),
    .w_tensor_6_8_V_rea(grp_gemm_core_fu_821_w_tensor_6_8_V_rea),
    .w_tensor_6_9_V_rea(grp_gemm_core_fu_821_w_tensor_6_9_V_rea),
    .w_tensor_6_10_V_re(grp_gemm_core_fu_821_w_tensor_6_10_V_re),
    .w_tensor_6_11_V_re(grp_gemm_core_fu_821_w_tensor_6_11_V_re),
    .w_tensor_6_12_V_re(grp_gemm_core_fu_821_w_tensor_6_12_V_re),
    .w_tensor_6_13_V_re(grp_gemm_core_fu_821_w_tensor_6_13_V_re),
    .w_tensor_6_14_V_re(grp_gemm_core_fu_821_w_tensor_6_14_V_re),
    .w_tensor_6_15_V_re(grp_gemm_core_fu_821_w_tensor_6_15_V_re),
    .w_tensor_7_0_V_rea(grp_gemm_core_fu_821_w_tensor_7_0_V_rea),
    .w_tensor_7_1_V_rea(grp_gemm_core_fu_821_w_tensor_7_1_V_rea),
    .w_tensor_7_2_V_rea(grp_gemm_core_fu_821_w_tensor_7_2_V_rea),
    .w_tensor_7_3_V_rea(grp_gemm_core_fu_821_w_tensor_7_3_V_rea),
    .w_tensor_7_4_V_rea(grp_gemm_core_fu_821_w_tensor_7_4_V_rea),
    .w_tensor_7_5_V_rea(grp_gemm_core_fu_821_w_tensor_7_5_V_rea),
    .w_tensor_7_6_V_rea(grp_gemm_core_fu_821_w_tensor_7_6_V_rea),
    .w_tensor_7_7_V_rea(grp_gemm_core_fu_821_w_tensor_7_7_V_rea),
    .w_tensor_7_8_V_rea(grp_gemm_core_fu_821_w_tensor_7_8_V_rea),
    .w_tensor_7_9_V_rea(grp_gemm_core_fu_821_w_tensor_7_9_V_rea),
    .w_tensor_7_10_V_re(grp_gemm_core_fu_821_w_tensor_7_10_V_re),
    .w_tensor_7_11_V_re(grp_gemm_core_fu_821_w_tensor_7_11_V_re),
    .w_tensor_7_12_V_re(grp_gemm_core_fu_821_w_tensor_7_12_V_re),
    .w_tensor_7_13_V_re(grp_gemm_core_fu_821_w_tensor_7_13_V_re),
    .w_tensor_7_14_V_re(grp_gemm_core_fu_821_w_tensor_7_14_V_re),
    .w_tensor_7_15_V_re(grp_gemm_core_fu_821_w_tensor_7_15_V_re),
    .w_tensor_8_0_V_rea(grp_gemm_core_fu_821_w_tensor_8_0_V_rea),
    .w_tensor_8_1_V_rea(grp_gemm_core_fu_821_w_tensor_8_1_V_rea),
    .w_tensor_8_2_V_rea(grp_gemm_core_fu_821_w_tensor_8_2_V_rea),
    .w_tensor_8_3_V_rea(grp_gemm_core_fu_821_w_tensor_8_3_V_rea),
    .w_tensor_8_4_V_rea(grp_gemm_core_fu_821_w_tensor_8_4_V_rea),
    .w_tensor_8_5_V_rea(grp_gemm_core_fu_821_w_tensor_8_5_V_rea),
    .w_tensor_8_6_V_rea(grp_gemm_core_fu_821_w_tensor_8_6_V_rea),
    .w_tensor_8_7_V_rea(grp_gemm_core_fu_821_w_tensor_8_7_V_rea),
    .w_tensor_8_8_V_rea(grp_gemm_core_fu_821_w_tensor_8_8_V_rea),
    .w_tensor_8_9_V_rea(grp_gemm_core_fu_821_w_tensor_8_9_V_rea),
    .w_tensor_8_10_V_re(grp_gemm_core_fu_821_w_tensor_8_10_V_re),
    .w_tensor_8_11_V_re(grp_gemm_core_fu_821_w_tensor_8_11_V_re),
    .w_tensor_8_12_V_re(grp_gemm_core_fu_821_w_tensor_8_12_V_re),
    .w_tensor_8_13_V_re(grp_gemm_core_fu_821_w_tensor_8_13_V_re),
    .w_tensor_8_14_V_re(grp_gemm_core_fu_821_w_tensor_8_14_V_re),
    .w_tensor_8_15_V_re(grp_gemm_core_fu_821_w_tensor_8_15_V_re),
    .w_tensor_9_0_V_rea(grp_gemm_core_fu_821_w_tensor_9_0_V_rea),
    .w_tensor_9_1_V_rea(grp_gemm_core_fu_821_w_tensor_9_1_V_rea),
    .w_tensor_9_2_V_rea(grp_gemm_core_fu_821_w_tensor_9_2_V_rea),
    .w_tensor_9_3_V_rea(grp_gemm_core_fu_821_w_tensor_9_3_V_rea),
    .w_tensor_9_4_V_rea(grp_gemm_core_fu_821_w_tensor_9_4_V_rea),
    .w_tensor_9_5_V_rea(grp_gemm_core_fu_821_w_tensor_9_5_V_rea),
    .w_tensor_9_6_V_rea(grp_gemm_core_fu_821_w_tensor_9_6_V_rea),
    .w_tensor_9_7_V_rea(grp_gemm_core_fu_821_w_tensor_9_7_V_rea),
    .w_tensor_9_8_V_rea(grp_gemm_core_fu_821_w_tensor_9_8_V_rea),
    .w_tensor_9_9_V_rea(grp_gemm_core_fu_821_w_tensor_9_9_V_rea),
    .w_tensor_9_10_V_re(grp_gemm_core_fu_821_w_tensor_9_10_V_re),
    .w_tensor_9_11_V_re(grp_gemm_core_fu_821_w_tensor_9_11_V_re),
    .w_tensor_9_12_V_re(grp_gemm_core_fu_821_w_tensor_9_12_V_re),
    .w_tensor_9_13_V_re(grp_gemm_core_fu_821_w_tensor_9_13_V_re),
    .w_tensor_9_14_V_re(grp_gemm_core_fu_821_w_tensor_9_14_V_re),
    .w_tensor_9_15_V_re(grp_gemm_core_fu_821_w_tensor_9_15_V_re),
    .w_tensor_10_0_V_re(grp_gemm_core_fu_821_w_tensor_10_0_V_re),
    .w_tensor_10_1_V_re(grp_gemm_core_fu_821_w_tensor_10_1_V_re),
    .w_tensor_10_2_V_re(grp_gemm_core_fu_821_w_tensor_10_2_V_re),
    .w_tensor_10_3_V_re(grp_gemm_core_fu_821_w_tensor_10_3_V_re),
    .w_tensor_10_4_V_re(grp_gemm_core_fu_821_w_tensor_10_4_V_re),
    .w_tensor_10_5_V_re(grp_gemm_core_fu_821_w_tensor_10_5_V_re),
    .w_tensor_10_6_V_re(grp_gemm_core_fu_821_w_tensor_10_6_V_re),
    .w_tensor_10_7_V_re(grp_gemm_core_fu_821_w_tensor_10_7_V_re),
    .w_tensor_10_8_V_re(grp_gemm_core_fu_821_w_tensor_10_8_V_re),
    .w_tensor_10_9_V_re(grp_gemm_core_fu_821_w_tensor_10_9_V_re),
    .w_tensor_10_10_V_r(grp_gemm_core_fu_821_w_tensor_10_10_V_r),
    .w_tensor_10_11_V_r(grp_gemm_core_fu_821_w_tensor_10_11_V_r),
    .w_tensor_10_12_V_r(grp_gemm_core_fu_821_w_tensor_10_12_V_r),
    .w_tensor_10_13_V_r(grp_gemm_core_fu_821_w_tensor_10_13_V_r),
    .w_tensor_10_14_V_r(grp_gemm_core_fu_821_w_tensor_10_14_V_r),
    .w_tensor_10_15_V_r(grp_gemm_core_fu_821_w_tensor_10_15_V_r),
    .w_tensor_11_0_V_re(grp_gemm_core_fu_821_w_tensor_11_0_V_re),
    .w_tensor_11_1_V_re(grp_gemm_core_fu_821_w_tensor_11_1_V_re),
    .w_tensor_11_2_V_re(grp_gemm_core_fu_821_w_tensor_11_2_V_re),
    .w_tensor_11_3_V_re(grp_gemm_core_fu_821_w_tensor_11_3_V_re),
    .w_tensor_11_4_V_re(grp_gemm_core_fu_821_w_tensor_11_4_V_re),
    .w_tensor_11_5_V_re(grp_gemm_core_fu_821_w_tensor_11_5_V_re),
    .w_tensor_11_6_V_re(grp_gemm_core_fu_821_w_tensor_11_6_V_re),
    .w_tensor_11_7_V_re(grp_gemm_core_fu_821_w_tensor_11_7_V_re),
    .w_tensor_11_8_V_re(grp_gemm_core_fu_821_w_tensor_11_8_V_re),
    .w_tensor_11_9_V_re(grp_gemm_core_fu_821_w_tensor_11_9_V_re),
    .w_tensor_11_10_V_r(grp_gemm_core_fu_821_w_tensor_11_10_V_r),
    .w_tensor_11_11_V_r(grp_gemm_core_fu_821_w_tensor_11_11_V_r),
    .w_tensor_11_12_V_r(grp_gemm_core_fu_821_w_tensor_11_12_V_r),
    .w_tensor_11_13_V_r(grp_gemm_core_fu_821_w_tensor_11_13_V_r),
    .w_tensor_11_14_V_r(grp_gemm_core_fu_821_w_tensor_11_14_V_r),
    .w_tensor_11_15_V_r(grp_gemm_core_fu_821_w_tensor_11_15_V_r),
    .w_tensor_12_0_V_re(grp_gemm_core_fu_821_w_tensor_12_0_V_re),
    .w_tensor_12_1_V_re(grp_gemm_core_fu_821_w_tensor_12_1_V_re),
    .w_tensor_12_2_V_re(grp_gemm_core_fu_821_w_tensor_12_2_V_re),
    .w_tensor_12_3_V_re(grp_gemm_core_fu_821_w_tensor_12_3_V_re),
    .w_tensor_12_4_V_re(grp_gemm_core_fu_821_w_tensor_12_4_V_re),
    .w_tensor_12_5_V_re(grp_gemm_core_fu_821_w_tensor_12_5_V_re),
    .w_tensor_12_6_V_re(grp_gemm_core_fu_821_w_tensor_12_6_V_re),
    .w_tensor_12_7_V_re(grp_gemm_core_fu_821_w_tensor_12_7_V_re),
    .w_tensor_12_8_V_re(grp_gemm_core_fu_821_w_tensor_12_8_V_re),
    .w_tensor_12_9_V_re(grp_gemm_core_fu_821_w_tensor_12_9_V_re),
    .w_tensor_12_10_V_r(grp_gemm_core_fu_821_w_tensor_12_10_V_r),
    .w_tensor_12_11_V_r(grp_gemm_core_fu_821_w_tensor_12_11_V_r),
    .w_tensor_12_12_V_r(grp_gemm_core_fu_821_w_tensor_12_12_V_r),
    .w_tensor_12_13_V_r(grp_gemm_core_fu_821_w_tensor_12_13_V_r),
    .w_tensor_12_14_V_r(grp_gemm_core_fu_821_w_tensor_12_14_V_r),
    .w_tensor_12_15_V_r(grp_gemm_core_fu_821_w_tensor_12_15_V_r),
    .w_tensor_13_0_V_re(grp_gemm_core_fu_821_w_tensor_13_0_V_re),
    .w_tensor_13_1_V_re(grp_gemm_core_fu_821_w_tensor_13_1_V_re),
    .w_tensor_13_2_V_re(grp_gemm_core_fu_821_w_tensor_13_2_V_re),
    .w_tensor_13_3_V_re(grp_gemm_core_fu_821_w_tensor_13_3_V_re),
    .w_tensor_13_4_V_re(grp_gemm_core_fu_821_w_tensor_13_4_V_re),
    .w_tensor_13_5_V_re(grp_gemm_core_fu_821_w_tensor_13_5_V_re),
    .w_tensor_13_6_V_re(grp_gemm_core_fu_821_w_tensor_13_6_V_re),
    .w_tensor_13_7_V_re(grp_gemm_core_fu_821_w_tensor_13_7_V_re),
    .w_tensor_13_8_V_re(grp_gemm_core_fu_821_w_tensor_13_8_V_re),
    .w_tensor_13_9_V_re(grp_gemm_core_fu_821_w_tensor_13_9_V_re),
    .w_tensor_13_10_V_r(grp_gemm_core_fu_821_w_tensor_13_10_V_r),
    .w_tensor_13_11_V_r(grp_gemm_core_fu_821_w_tensor_13_11_V_r),
    .w_tensor_13_12_V_r(grp_gemm_core_fu_821_w_tensor_13_12_V_r),
    .w_tensor_13_13_V_r(grp_gemm_core_fu_821_w_tensor_13_13_V_r),
    .w_tensor_13_14_V_r(grp_gemm_core_fu_821_w_tensor_13_14_V_r),
    .w_tensor_13_15_V_r(grp_gemm_core_fu_821_w_tensor_13_15_V_r),
    .w_tensor_14_0_V_re(grp_gemm_core_fu_821_w_tensor_14_0_V_re),
    .w_tensor_14_1_V_re(grp_gemm_core_fu_821_w_tensor_14_1_V_re),
    .w_tensor_14_2_V_re(grp_gemm_core_fu_821_w_tensor_14_2_V_re),
    .w_tensor_14_3_V_re(grp_gemm_core_fu_821_w_tensor_14_3_V_re),
    .w_tensor_14_4_V_re(grp_gemm_core_fu_821_w_tensor_14_4_V_re),
    .w_tensor_14_5_V_re(grp_gemm_core_fu_821_w_tensor_14_5_V_re),
    .w_tensor_14_6_V_re(grp_gemm_core_fu_821_w_tensor_14_6_V_re),
    .w_tensor_14_7_V_re(grp_gemm_core_fu_821_w_tensor_14_7_V_re),
    .w_tensor_14_8_V_re(grp_gemm_core_fu_821_w_tensor_14_8_V_re),
    .w_tensor_14_9_V_re(grp_gemm_core_fu_821_w_tensor_14_9_V_re),
    .w_tensor_14_10_V_r(grp_gemm_core_fu_821_w_tensor_14_10_V_r),
    .w_tensor_14_11_V_r(grp_gemm_core_fu_821_w_tensor_14_11_V_r),
    .w_tensor_14_12_V_r(grp_gemm_core_fu_821_w_tensor_14_12_V_r),
    .w_tensor_14_13_V_r(grp_gemm_core_fu_821_w_tensor_14_13_V_r),
    .w_tensor_14_14_V_r(grp_gemm_core_fu_821_w_tensor_14_14_V_r),
    .w_tensor_14_15_V_r(grp_gemm_core_fu_821_w_tensor_14_15_V_r),
    .w_tensor_15_0_V_re(grp_gemm_core_fu_821_w_tensor_15_0_V_re),
    .w_tensor_15_1_V_re(grp_gemm_core_fu_821_w_tensor_15_1_V_re),
    .w_tensor_15_2_V_re(grp_gemm_core_fu_821_w_tensor_15_2_V_re),
    .w_tensor_15_3_V_re(grp_gemm_core_fu_821_w_tensor_15_3_V_re),
    .w_tensor_15_4_V_re(grp_gemm_core_fu_821_w_tensor_15_4_V_re),
    .w_tensor_15_5_V_re(grp_gemm_core_fu_821_w_tensor_15_5_V_re),
    .w_tensor_15_6_V_re(grp_gemm_core_fu_821_w_tensor_15_6_V_re),
    .w_tensor_15_7_V_re(grp_gemm_core_fu_821_w_tensor_15_7_V_re),
    .w_tensor_15_8_V_re(grp_gemm_core_fu_821_w_tensor_15_8_V_re),
    .w_tensor_15_9_V_re(grp_gemm_core_fu_821_w_tensor_15_9_V_re),
    .w_tensor_15_10_V_r(grp_gemm_core_fu_821_w_tensor_15_10_V_r),
    .w_tensor_15_11_V_r(grp_gemm_core_fu_821_w_tensor_15_11_V_r),
    .w_tensor_15_12_V_r(grp_gemm_core_fu_821_w_tensor_15_12_V_r),
    .w_tensor_15_13_V_r(grp_gemm_core_fu_821_w_tensor_15_13_V_r),
    .w_tensor_15_14_V_r(grp_gemm_core_fu_821_w_tensor_15_14_V_r),
    .w_tensor_15_15_V_r(grp_gemm_core_fu_821_w_tensor_15_15_V_r),
    .a_tensor_0_0_V_rea(grp_gemm_core_fu_821_a_tensor_0_0_V_rea),
    .a_tensor_0_1_V_rea(grp_gemm_core_fu_821_a_tensor_0_1_V_rea),
    .a_tensor_0_2_V_rea(grp_gemm_core_fu_821_a_tensor_0_2_V_rea),
    .a_tensor_0_3_V_rea(grp_gemm_core_fu_821_a_tensor_0_3_V_rea),
    .a_tensor_0_4_V_rea(grp_gemm_core_fu_821_a_tensor_0_4_V_rea),
    .a_tensor_0_5_V_rea(grp_gemm_core_fu_821_a_tensor_0_5_V_rea),
    .a_tensor_0_6_V_rea(grp_gemm_core_fu_821_a_tensor_0_6_V_rea),
    .a_tensor_0_7_V_rea(grp_gemm_core_fu_821_a_tensor_0_7_V_rea),
    .a_tensor_0_8_V_rea(grp_gemm_core_fu_821_a_tensor_0_8_V_rea),
    .a_tensor_0_9_V_rea(grp_gemm_core_fu_821_a_tensor_0_9_V_rea),
    .a_tensor_0_10_V_re(grp_gemm_core_fu_821_a_tensor_0_10_V_re),
    .a_tensor_0_11_V_re(grp_gemm_core_fu_821_a_tensor_0_11_V_re),
    .a_tensor_0_12_V_re(grp_gemm_core_fu_821_a_tensor_0_12_V_re),
    .a_tensor_0_13_V_re(grp_gemm_core_fu_821_a_tensor_0_13_V_re),
    .a_tensor_0_14_V_re(grp_gemm_core_fu_821_a_tensor_0_14_V_re),
    .a_tensor_0_15_V_re(grp_gemm_core_fu_821_a_tensor_0_15_V_re),
    .gemm_reset(grp_gemm_core_fu_821_gemm_reset),
    .ap_return_0(grp_gemm_core_fu_821_ap_return_0),
    .ap_return_1(grp_gemm_core_fu_821_ap_return_1),
    .ap_return_2(grp_gemm_core_fu_821_ap_return_2),
    .ap_return_3(grp_gemm_core_fu_821_ap_return_3),
    .ap_return_4(grp_gemm_core_fu_821_ap_return_4),
    .ap_return_5(grp_gemm_core_fu_821_ap_return_5),
    .ap_return_6(grp_gemm_core_fu_821_ap_return_6),
    .ap_return_7(grp_gemm_core_fu_821_ap_return_7),
    .ap_return_8(grp_gemm_core_fu_821_ap_return_8),
    .ap_return_9(grp_gemm_core_fu_821_ap_return_9),
    .ap_return_10(grp_gemm_core_fu_821_ap_return_10),
    .ap_return_11(grp_gemm_core_fu_821_ap_return_11),
    .ap_return_12(grp_gemm_core_fu_821_ap_return_12),
    .ap_return_13(grp_gemm_core_fu_821_ap_return_13),
    .ap_return_14(grp_gemm_core_fu_821_ap_return_14),
    .ap_return_15(grp_gemm_core_fu_821_ap_return_15),
    .ap_return_16(grp_gemm_core_fu_821_ap_return_16),
    .ap_return_17(grp_gemm_core_fu_821_ap_return_17),
    .ap_return_18(grp_gemm_core_fu_821_ap_return_18),
    .ap_return_19(grp_gemm_core_fu_821_ap_return_19),
    .ap_return_20(grp_gemm_core_fu_821_ap_return_20),
    .ap_return_21(grp_gemm_core_fu_821_ap_return_21),
    .ap_return_22(grp_gemm_core_fu_821_ap_return_22),
    .ap_return_23(grp_gemm_core_fu_821_ap_return_23),
    .ap_return_24(grp_gemm_core_fu_821_ap_return_24),
    .ap_return_25(grp_gemm_core_fu_821_ap_return_25),
    .ap_return_26(grp_gemm_core_fu_821_ap_return_26),
    .ap_return_27(grp_gemm_core_fu_821_ap_return_27),
    .ap_return_28(grp_gemm_core_fu_821_ap_return_28),
    .ap_return_29(grp_gemm_core_fu_821_ap_return_29),
    .ap_return_30(grp_gemm_core_fu_821_ap_return_30),
    .ap_return_31(grp_gemm_core_fu_821_ap_return_31)
);

always @ (posedge ap_clk) begin           // set ap_CS_fsm 
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp0_exit_iter0_state4) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((icmp_iter_in == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((((1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b1 == ap_CS_fsm_pp0_stage0)))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((icmp_iter_in == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        dst_offset_in_0_reg_767 <= dst_offset_in_V_1_fu_4691_p2;
    end else if (((icmp_iter_out == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        dst_offset_in_0_reg_767 <= dst_offset_in_V_reg_720;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_iter_in == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        dst_offset_in_V_reg_720 <= dst_offset_out_V_fu_1202_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        dst_offset_in_V_reg_720 <= 12'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        iter_in_reg <= it_in_reg_4775;
    end else if (((icmp_iter_out == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        iter_in_reg <= 14'd0;
    end
end

always @ (posedge ap_clk) begin  // 
    if (((icmp_iter_in == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        iter_out_reg <= it_out_reg_4761;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        iter_out_reg <= 14'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        src_offset_in_0_reg_778 <= src_offset_in_V_1_fu_4710_p2;
    end else if (((icmp_iter_out == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        src_offset_in_0_reg_778 <= src_offset_in_V_reg_732;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_iter_in == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        src_offset_in_V_reg_732 <= src_offset_out_V_fu_1221_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        src_offset_in_V_reg_732 <= 12'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln35_reg_4805 == 1'd1))) begin
        upc_0_reg_811 <= upc_1_reg_6279;
    end else if (((icmp_iter_in == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        upc_0_reg_811 <= upc_fu_1172_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        wgt_offset_in_0_reg_789 <= wgt_offset_in_V_1_fu_4729_p2;
    end else if (((icmp_iter_out == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        wgt_offset_in_0_reg_789 <= wgt_offset_in_V_reg_744;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_iter_in == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        wgt_offset_in_V_reg_744 <= wgt_offset_out_V_fu_1240_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        wgt_offset_in_V_reg_744 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln35_reg_4805 == 1'd1))) begin
        acc_mem_V_1_addr_reg_4834 <= zext_ln544_2_fu_1321_p1;
        zext_ln544_2_reg_4829[11 : 0] <= zext_ln544_2_fu_1321_p1[11 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        gemm_reset_reg_4748 <= insn_raw_V[32'd7];
        inst_iter_out_reg <= {{insn_raw_V[48:35]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln35_reg_4805 <= icmp_ln35_fu_1246_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        it_in_reg_4775 <= it_in_fu_1157_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        it_out_reg_4761 <= it_out_fu_1137_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_iter_out == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        inst_iter_in_reg <= {{insn_raw_V[62:49]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (icmp_ln35_reg_4805 == 1'd1))) begin
        upc_1_reg_6279 <= upc_1_fu_4470_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_iter_in == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        zext_ln35_reg_4785[13 : 0] <= zext_ln35_fu_1185_p1[13 : 0];
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_mem_V_2_address0 = acc_mem_V_1_addr_reg_4834;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        acc_mem_V_2_address0 = zext_ln544_2_fu_1321_p1;
    end else begin
        acc_mem_V_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        acc_mem_V_2_ce0 = 1'b1;
    end else begin
        acc_mem_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln35_reg_4805 == 1'd1))) begin
        acc_mem_V_2_we0 = 64'd18446744073709551615;
    end else begin
        acc_mem_V_2_we0 = 64'd0;
    end
end

always @ (*) begin
    if ((icmp_ln35_fu_1246_p2 == 1'd0)) begin
        ap_condition_pp0_exit_iter0_state4 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state4 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_iter_out == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln35_reg_4805 == 1'd1))) begin
        ap_phi_mux_upc_0_phi_fu_814_p4 = upc_1_reg_6279;
    end else begin
        ap_phi_mux_upc_0_phi_fu_814_p4 = upc_0_reg_811;
    end
end

always @ (*) begin
    if (((icmp_iter_out == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        inp_mem_V_EN_A = 1'b1;
    end else begin
        inp_mem_V_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) )) begin
        out_mem_V_EN_A = 1'b1;
    end else begin
        out_mem_V_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln35_reg_4805 == 1'd1))) begin
        out_mem_V_WEN_A = 16'd65535;
    end else begin
        out_mem_V_WEN_A = 16'd0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        uop_mem_V_2_ce0 = 1'b1;
    end else begin
        uop_mem_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        wgt_mem_0_V_EN_A = 1'b1;
    end else begin
        wgt_mem_0_V_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        wgt_mem_1_V_EN_A = 1'b1;
    end else begin
        wgt_mem_1_V_EN_A = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin  //
            if (((icmp_iter_out == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_iter_in == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((icmp_ln35_fu_1246_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((icmp_ln35_fu_1246_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage2;
        end

        ap_ST_fsm_pp0_stage2 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage3;
        end

        ap_ST_fsm_pp0_stage3 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage4;
        end

        ap_ST_fsm_pp0_stage4 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage5;
        end

        ap_ST_fsm_pp0_stage5 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end

        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_mem_V_2_d0 = {{{{{{{{{{{{{{{{grp_gemm_core_fu_821_ap_return_15}, {grp_gemm_core_fu_821_ap_return_14}}, {grp_gemm_core_fu_821_ap_return_13}}, {grp_gemm_core_fu_821_ap_return_12}}, {grp_gemm_core_fu_821_ap_return_11}}, {grp_gemm_core_fu_821_ap_return_10}}, {grp_gemm_core_fu_821_ap_return_9}}, {grp_gemm_core_fu_821_ap_return_8}}, {grp_gemm_core_fu_821_ap_return_7}}, {grp_gemm_core_fu_821_ap_return_6}}, {grp_gemm_core_fu_821_ap_return_5}}, {grp_gemm_core_fu_821_ap_return_4}}, {grp_gemm_core_fu_821_ap_return_3}}, {grp_gemm_core_fu_821_ap_return_2}}, {grp_gemm_core_fu_821_ap_return_1}}, {grp_gemm_core_fu_821_ap_return_0}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign dst_idx_V_fu_1264_p2 = (zext_ln209_fu_1260_p1 + dst_offset_in_0_reg_767);

assign dst_offset_in_V_1_fu_4691_p2 = (zext_ln700_3_fu_4687_p1 + dst_offset_in_0_reg_767);

assign dst_offset_out_V_fu_1202_p2 = (zext_ln700_fu_1198_p1 + dst_offset_in_V_reg_720);

assign grp_gemm_core_fu_821_a_tensor_0_0_V_rea = acc_mem_V_2_q0[31:0];

assign grp_gemm_core_fu_821_a_tensor_0_10_V_re = {{acc_mem_V_2_q0[351:320]}};

assign grp_gemm_core_fu_821_a_tensor_0_11_V_re = {{acc_mem_V_2_q0[383:352]}};

assign grp_gemm_core_fu_821_a_tensor_0_12_V_re = {{acc_mem_V_2_q0[415:384]}};

assign grp_gemm_core_fu_821_a_tensor_0_13_V_re = {{acc_mem_V_2_q0[447:416]}};

assign grp_gemm_core_fu_821_a_tensor_0_14_V_re = {{acc_mem_V_2_q0[479:448]}};

assign grp_gemm_core_fu_821_a_tensor_0_15_V_re = {{acc_mem_V_2_q0[511:480]}};

assign grp_gemm_core_fu_821_a_tensor_0_1_V_rea = {{acc_mem_V_2_q0[63:32]}};

assign grp_gemm_core_fu_821_a_tensor_0_2_V_rea = {{acc_mem_V_2_q0[95:64]}};

assign grp_gemm_core_fu_821_a_tensor_0_3_V_rea = {{acc_mem_V_2_q0[127:96]}};

assign grp_gemm_core_fu_821_a_tensor_0_4_V_rea = {{acc_mem_V_2_q0[159:128]}};

assign grp_gemm_core_fu_821_a_tensor_0_5_V_rea = {{acc_mem_V_2_q0[191:160]}};

assign grp_gemm_core_fu_821_a_tensor_0_6_V_rea = {{acc_mem_V_2_q0[223:192]}};

assign grp_gemm_core_fu_821_a_tensor_0_7_V_rea = {{acc_mem_V_2_q0[255:224]}};

assign grp_gemm_core_fu_821_a_tensor_0_8_V_rea = {{acc_mem_V_2_q0[287:256]}};

assign grp_gemm_core_fu_821_a_tensor_0_9_V_rea = {{acc_mem_V_2_q0[319:288]}};

assign grp_gemm_core_fu_821_gemm_reset = gemm_reset_reg_4748;

assign grp_gemm_core_fu_821_i_tensor_0_0_V_rea = inp_mem_V_Dout_A[7:0];

assign grp_gemm_core_fu_821_i_tensor_0_10_V_re = {{inp_mem_V_Dout_A[87:80]}};

assign grp_gemm_core_fu_821_i_tensor_0_11_V_re = {{inp_mem_V_Dout_A[95:88]}};

assign grp_gemm_core_fu_821_i_tensor_0_12_V_re = {{inp_mem_V_Dout_A[103:96]}};

assign grp_gemm_core_fu_821_i_tensor_0_13_V_re = {{inp_mem_V_Dout_A[111:104]}};

assign grp_gemm_core_fu_821_i_tensor_0_14_V_re = {{inp_mem_V_Dout_A[119:112]}};

assign grp_gemm_core_fu_821_i_tensor_0_15_V_re = {{inp_mem_V_Dout_A[127:120]}};

assign grp_gemm_core_fu_821_i_tensor_0_1_V_rea = {{inp_mem_V_Dout_A[15:8]}};

assign grp_gemm_core_fu_821_i_tensor_0_2_V_rea = {{inp_mem_V_Dout_A[23:16]}};

assign grp_gemm_core_fu_821_i_tensor_0_3_V_rea = {{inp_mem_V_Dout_A[31:24]}};

assign grp_gemm_core_fu_821_i_tensor_0_4_V_rea = {{inp_mem_V_Dout_A[39:32]}};

assign grp_gemm_core_fu_821_i_tensor_0_5_V_rea = {{inp_mem_V_Dout_A[47:40]}};

assign grp_gemm_core_fu_821_i_tensor_0_6_V_rea = {{inp_mem_V_Dout_A[55:48]}};

assign grp_gemm_core_fu_821_i_tensor_0_7_V_rea = {{inp_mem_V_Dout_A[63:56]}};

assign grp_gemm_core_fu_821_i_tensor_0_8_V_rea = {{inp_mem_V_Dout_A[71:64]}};

assign grp_gemm_core_fu_821_i_tensor_0_9_V_rea = {{inp_mem_V_Dout_A[79:72]}};

assign grp_gemm_core_fu_821_w_tensor_0_0_V_rea = wgt_mem_0_V_Dout_A[7:0];

assign grp_gemm_core_fu_821_w_tensor_0_10_V_re = {{wgt_mem_1_V_Dout_A[23:16]}};

assign grp_gemm_core_fu_821_w_tensor_0_11_V_re = {{wgt_mem_1_V_Dout_A[31:24]}};

assign grp_gemm_core_fu_821_w_tensor_0_12_V_re = {{wgt_mem_1_V_Dout_A[39:32]}};

assign grp_gemm_core_fu_821_w_tensor_0_13_V_re = {{wgt_mem_1_V_Dout_A[47:40]}};

assign grp_gemm_core_fu_821_w_tensor_0_14_V_re = {{wgt_mem_1_V_Dout_A[55:48]}};

assign grp_gemm_core_fu_821_w_tensor_0_15_V_re = {{wgt_mem_1_V_Dout_A[63:56]}};

assign grp_gemm_core_fu_821_w_tensor_0_1_V_rea = {{wgt_mem_0_V_Dout_A[15:8]}};

assign grp_gemm_core_fu_821_w_tensor_0_2_V_rea = {{wgt_mem_0_V_Dout_A[23:16]}};

assign grp_gemm_core_fu_821_w_tensor_0_3_V_rea = {{wgt_mem_0_V_Dout_A[31:24]}};

assign grp_gemm_core_fu_821_w_tensor_0_4_V_rea = {{wgt_mem_0_V_Dout_A[39:32]}};

assign grp_gemm_core_fu_821_w_tensor_0_5_V_rea = {{wgt_mem_0_V_Dout_A[47:40]}};

assign grp_gemm_core_fu_821_w_tensor_0_6_V_rea = {{wgt_mem_0_V_Dout_A[55:48]}};

assign grp_gemm_core_fu_821_w_tensor_0_7_V_rea = {{wgt_mem_0_V_Dout_A[63:56]}};

assign grp_gemm_core_fu_821_w_tensor_0_8_V_rea = wgt_mem_1_V_Dout_A[7:0];

assign grp_gemm_core_fu_821_w_tensor_0_9_V_rea = {{wgt_mem_1_V_Dout_A[15:8]}};

assign grp_gemm_core_fu_821_w_tensor_10_0_V_re = {{wgt_mem_0_V_Dout_A[647:640]}};

assign grp_gemm_core_fu_821_w_tensor_10_10_V_r = {{wgt_mem_1_V_Dout_A[663:656]}};

assign grp_gemm_core_fu_821_w_tensor_10_11_V_r = {{wgt_mem_1_V_Dout_A[671:664]}};

assign grp_gemm_core_fu_821_w_tensor_10_12_V_r = {{wgt_mem_1_V_Dout_A[679:672]}};

assign grp_gemm_core_fu_821_w_tensor_10_13_V_r = {{wgt_mem_1_V_Dout_A[687:680]}};

assign grp_gemm_core_fu_821_w_tensor_10_14_V_r = {{wgt_mem_1_V_Dout_A[695:688]}};

assign grp_gemm_core_fu_821_w_tensor_10_15_V_r = {{wgt_mem_1_V_Dout_A[703:696]}};

assign grp_gemm_core_fu_821_w_tensor_10_1_V_re = {{wgt_mem_0_V_Dout_A[655:648]}};

assign grp_gemm_core_fu_821_w_tensor_10_2_V_re = {{wgt_mem_0_V_Dout_A[663:656]}};

assign grp_gemm_core_fu_821_w_tensor_10_3_V_re = {{wgt_mem_0_V_Dout_A[671:664]}};

assign grp_gemm_core_fu_821_w_tensor_10_4_V_re = {{wgt_mem_0_V_Dout_A[679:672]}};

assign grp_gemm_core_fu_821_w_tensor_10_5_V_re = {{wgt_mem_0_V_Dout_A[687:680]}};

assign grp_gemm_core_fu_821_w_tensor_10_6_V_re = {{wgt_mem_0_V_Dout_A[695:688]}};

assign grp_gemm_core_fu_821_w_tensor_10_7_V_re = {{wgt_mem_0_V_Dout_A[703:696]}};

assign grp_gemm_core_fu_821_w_tensor_10_8_V_re = {{wgt_mem_1_V_Dout_A[647:640]}};

assign grp_gemm_core_fu_821_w_tensor_10_9_V_re = {{wgt_mem_1_V_Dout_A[655:648]}};

assign grp_gemm_core_fu_821_w_tensor_11_0_V_re = {{wgt_mem_0_V_Dout_A[711:704]}};

assign grp_gemm_core_fu_821_w_tensor_11_10_V_r = {{wgt_mem_1_V_Dout_A[727:720]}};

assign grp_gemm_core_fu_821_w_tensor_11_11_V_r = {{wgt_mem_1_V_Dout_A[735:728]}};

assign grp_gemm_core_fu_821_w_tensor_11_12_V_r = {{wgt_mem_1_V_Dout_A[743:736]}};

assign grp_gemm_core_fu_821_w_tensor_11_13_V_r = {{wgt_mem_1_V_Dout_A[751:744]}};

assign grp_gemm_core_fu_821_w_tensor_11_14_V_r = {{wgt_mem_1_V_Dout_A[759:752]}};

assign grp_gemm_core_fu_821_w_tensor_11_15_V_r = {{wgt_mem_1_V_Dout_A[767:760]}};

assign grp_gemm_core_fu_821_w_tensor_11_1_V_re = {{wgt_mem_0_V_Dout_A[719:712]}};

assign grp_gemm_core_fu_821_w_tensor_11_2_V_re = {{wgt_mem_0_V_Dout_A[727:720]}};

assign grp_gemm_core_fu_821_w_tensor_11_3_V_re = {{wgt_mem_0_V_Dout_A[735:728]}};

assign grp_gemm_core_fu_821_w_tensor_11_4_V_re = {{wgt_mem_0_V_Dout_A[743:736]}};

assign grp_gemm_core_fu_821_w_tensor_11_5_V_re = {{wgt_mem_0_V_Dout_A[751:744]}};

assign grp_gemm_core_fu_821_w_tensor_11_6_V_re = {{wgt_mem_0_V_Dout_A[759:752]}};

assign grp_gemm_core_fu_821_w_tensor_11_7_V_re = {{wgt_mem_0_V_Dout_A[767:760]}};

assign grp_gemm_core_fu_821_w_tensor_11_8_V_re = {{wgt_mem_1_V_Dout_A[711:704]}};

assign grp_gemm_core_fu_821_w_tensor_11_9_V_re = {{wgt_mem_1_V_Dout_A[719:712]}};

assign grp_gemm_core_fu_821_w_tensor_12_0_V_re = {{wgt_mem_0_V_Dout_A[775:768]}};

assign grp_gemm_core_fu_821_w_tensor_12_10_V_r = {{wgt_mem_1_V_Dout_A[791:784]}};

assign grp_gemm_core_fu_821_w_tensor_12_11_V_r = {{wgt_mem_1_V_Dout_A[799:792]}};

assign grp_gemm_core_fu_821_w_tensor_12_12_V_r = {{wgt_mem_1_V_Dout_A[807:800]}};

assign grp_gemm_core_fu_821_w_tensor_12_13_V_r = {{wgt_mem_1_V_Dout_A[815:808]}};

assign grp_gemm_core_fu_821_w_tensor_12_14_V_r = {{wgt_mem_1_V_Dout_A[823:816]}};

assign grp_gemm_core_fu_821_w_tensor_12_15_V_r = {{wgt_mem_1_V_Dout_A[831:824]}};

assign grp_gemm_core_fu_821_w_tensor_12_1_V_re = {{wgt_mem_0_V_Dout_A[783:776]}};

assign grp_gemm_core_fu_821_w_tensor_12_2_V_re = {{wgt_mem_0_V_Dout_A[791:784]}};

assign grp_gemm_core_fu_821_w_tensor_12_3_V_re = {{wgt_mem_0_V_Dout_A[799:792]}};

assign grp_gemm_core_fu_821_w_tensor_12_4_V_re = {{wgt_mem_0_V_Dout_A[807:800]}};

assign grp_gemm_core_fu_821_w_tensor_12_5_V_re = {{wgt_mem_0_V_Dout_A[815:808]}};

assign grp_gemm_core_fu_821_w_tensor_12_6_V_re = {{wgt_mem_0_V_Dout_A[823:816]}};

assign grp_gemm_core_fu_821_w_tensor_12_7_V_re = {{wgt_mem_0_V_Dout_A[831:824]}};

assign grp_gemm_core_fu_821_w_tensor_12_8_V_re = {{wgt_mem_1_V_Dout_A[775:768]}};

assign grp_gemm_core_fu_821_w_tensor_12_9_V_re = {{wgt_mem_1_V_Dout_A[783:776]}};

assign grp_gemm_core_fu_821_w_tensor_13_0_V_re = {{wgt_mem_0_V_Dout_A[839:832]}};

assign grp_gemm_core_fu_821_w_tensor_13_10_V_r = {{wgt_mem_1_V_Dout_A[855:848]}};

assign grp_gemm_core_fu_821_w_tensor_13_11_V_r = {{wgt_mem_1_V_Dout_A[863:856]}};

assign grp_gemm_core_fu_821_w_tensor_13_12_V_r = {{wgt_mem_1_V_Dout_A[871:864]}};

assign grp_gemm_core_fu_821_w_tensor_13_13_V_r = {{wgt_mem_1_V_Dout_A[879:872]}};

assign grp_gemm_core_fu_821_w_tensor_13_14_V_r = {{wgt_mem_1_V_Dout_A[887:880]}};

assign grp_gemm_core_fu_821_w_tensor_13_15_V_r = {{wgt_mem_1_V_Dout_A[895:888]}};

assign grp_gemm_core_fu_821_w_tensor_13_1_V_re = {{wgt_mem_0_V_Dout_A[847:840]}};

assign grp_gemm_core_fu_821_w_tensor_13_2_V_re = {{wgt_mem_0_V_Dout_A[855:848]}};

assign grp_gemm_core_fu_821_w_tensor_13_3_V_re = {{wgt_mem_0_V_Dout_A[863:856]}};

assign grp_gemm_core_fu_821_w_tensor_13_4_V_re = {{wgt_mem_0_V_Dout_A[871:864]}};

assign grp_gemm_core_fu_821_w_tensor_13_5_V_re = {{wgt_mem_0_V_Dout_A[879:872]}};

assign grp_gemm_core_fu_821_w_tensor_13_6_V_re = {{wgt_mem_0_V_Dout_A[887:880]}};

assign grp_gemm_core_fu_821_w_tensor_13_7_V_re = {{wgt_mem_0_V_Dout_A[895:888]}};

assign grp_gemm_core_fu_821_w_tensor_13_8_V_re = {{wgt_mem_1_V_Dout_A[839:832]}};

assign grp_gemm_core_fu_821_w_tensor_13_9_V_re = {{wgt_mem_1_V_Dout_A[847:840]}};

assign grp_gemm_core_fu_821_w_tensor_14_0_V_re = {{wgt_mem_0_V_Dout_A[903:896]}};

assign grp_gemm_core_fu_821_w_tensor_14_10_V_r = {{wgt_mem_1_V_Dout_A[919:912]}};

assign grp_gemm_core_fu_821_w_tensor_14_11_V_r = {{wgt_mem_1_V_Dout_A[927:920]}};

assign grp_gemm_core_fu_821_w_tensor_14_12_V_r = {{wgt_mem_1_V_Dout_A[935:928]}};

assign grp_gemm_core_fu_821_w_tensor_14_13_V_r = {{wgt_mem_1_V_Dout_A[943:936]}};

assign grp_gemm_core_fu_821_w_tensor_14_14_V_r = {{wgt_mem_1_V_Dout_A[951:944]}};

assign grp_gemm_core_fu_821_w_tensor_14_15_V_r = {{wgt_mem_1_V_Dout_A[959:952]}};

assign grp_gemm_core_fu_821_w_tensor_14_1_V_re = {{wgt_mem_0_V_Dout_A[911:904]}};

assign grp_gemm_core_fu_821_w_tensor_14_2_V_re = {{wgt_mem_0_V_Dout_A[919:912]}};

assign grp_gemm_core_fu_821_w_tensor_14_3_V_re = {{wgt_mem_0_V_Dout_A[927:920]}};

assign grp_gemm_core_fu_821_w_tensor_14_4_V_re = {{wgt_mem_0_V_Dout_A[935:928]}};

assign grp_gemm_core_fu_821_w_tensor_14_5_V_re = {{wgt_mem_0_V_Dout_A[943:936]}};

assign grp_gemm_core_fu_821_w_tensor_14_6_V_re = {{wgt_mem_0_V_Dout_A[951:944]}};

assign grp_gemm_core_fu_821_w_tensor_14_7_V_re = {{wgt_mem_0_V_Dout_A[959:952]}};

assign grp_gemm_core_fu_821_w_tensor_14_8_V_re = {{wgt_mem_1_V_Dout_A[903:896]}};

assign grp_gemm_core_fu_821_w_tensor_14_9_V_re = {{wgt_mem_1_V_Dout_A[911:904]}};

assign grp_gemm_core_fu_821_w_tensor_15_0_V_re = {{wgt_mem_0_V_Dout_A[967:960]}};

assign grp_gemm_core_fu_821_w_tensor_15_10_V_r = {{wgt_mem_1_V_Dout_A[983:976]}};

assign grp_gemm_core_fu_821_w_tensor_15_11_V_r = {{wgt_mem_1_V_Dout_A[991:984]}};

assign grp_gemm_core_fu_821_w_tensor_15_12_V_r = {{wgt_mem_1_V_Dout_A[999:992]}};

assign grp_gemm_core_fu_821_w_tensor_15_13_V_r = {{wgt_mem_1_V_Dout_A[1007:1000]}};

assign grp_gemm_core_fu_821_w_tensor_15_14_V_r = {{wgt_mem_1_V_Dout_A[1015:1008]}};

assign grp_gemm_core_fu_821_w_tensor_15_15_V_r = {{wgt_mem_1_V_Dout_A[1023:1016]}};

assign grp_gemm_core_fu_821_w_tensor_15_1_V_re = {{wgt_mem_0_V_Dout_A[975:968]}};

assign grp_gemm_core_fu_821_w_tensor_15_2_V_re = {{wgt_mem_0_V_Dout_A[983:976]}};

assign grp_gemm_core_fu_821_w_tensor_15_3_V_re = {{wgt_mem_0_V_Dout_A[991:984]}};

assign grp_gemm_core_fu_821_w_tensor_15_4_V_re = {{wgt_mem_0_V_Dout_A[999:992]}};

assign grp_gemm_core_fu_821_w_tensor_15_5_V_re = {{wgt_mem_0_V_Dout_A[1007:1000]}};

assign grp_gemm_core_fu_821_w_tensor_15_6_V_re = {{wgt_mem_0_V_Dout_A[1015:1008]}};

assign grp_gemm_core_fu_821_w_tensor_15_7_V_re = {{wgt_mem_0_V_Dout_A[1023:1016]}};

assign grp_gemm_core_fu_821_w_tensor_15_8_V_re = {{wgt_mem_1_V_Dout_A[967:960]}};

assign grp_gemm_core_fu_821_w_tensor_15_9_V_re = {{wgt_mem_1_V_Dout_A[975:968]}};

assign grp_gemm_core_fu_821_w_tensor_1_0_V_rea = {{wgt_mem_0_V_Dout_A[71:64]}};

assign grp_gemm_core_fu_821_w_tensor_1_10_V_re = {{wgt_mem_1_V_Dout_A[87:80]}};

assign grp_gemm_core_fu_821_w_tensor_1_11_V_re = {{wgt_mem_1_V_Dout_A[95:88]}};

assign grp_gemm_core_fu_821_w_tensor_1_12_V_re = {{wgt_mem_1_V_Dout_A[103:96]}};

assign grp_gemm_core_fu_821_w_tensor_1_13_V_re = {{wgt_mem_1_V_Dout_A[111:104]}};

assign grp_gemm_core_fu_821_w_tensor_1_14_V_re = {{wgt_mem_1_V_Dout_A[119:112]}};

assign grp_gemm_core_fu_821_w_tensor_1_15_V_re = {{wgt_mem_1_V_Dout_A[127:120]}};

assign grp_gemm_core_fu_821_w_tensor_1_1_V_rea = {{wgt_mem_0_V_Dout_A[79:72]}};

assign grp_gemm_core_fu_821_w_tensor_1_2_V_rea = {{wgt_mem_0_V_Dout_A[87:80]}};

assign grp_gemm_core_fu_821_w_tensor_1_3_V_rea = {{wgt_mem_0_V_Dout_A[95:88]}};

assign grp_gemm_core_fu_821_w_tensor_1_4_V_rea = {{wgt_mem_0_V_Dout_A[103:96]}};

assign grp_gemm_core_fu_821_w_tensor_1_5_V_rea = {{wgt_mem_0_V_Dout_A[111:104]}};

assign grp_gemm_core_fu_821_w_tensor_1_6_V_rea = {{wgt_mem_0_V_Dout_A[119:112]}};

assign grp_gemm_core_fu_821_w_tensor_1_7_V_rea = {{wgt_mem_0_V_Dout_A[127:120]}};

assign grp_gemm_core_fu_821_w_tensor_1_8_V_rea = {{wgt_mem_1_V_Dout_A[71:64]}};

assign grp_gemm_core_fu_821_w_tensor_1_9_V_rea = {{wgt_mem_1_V_Dout_A[79:72]}};

assign grp_gemm_core_fu_821_w_tensor_2_0_V_rea = {{wgt_mem_0_V_Dout_A[135:128]}};

assign grp_gemm_core_fu_821_w_tensor_2_10_V_re = {{wgt_mem_1_V_Dout_A[151:144]}};

assign grp_gemm_core_fu_821_w_tensor_2_11_V_re = {{wgt_mem_1_V_Dout_A[159:152]}};

assign grp_gemm_core_fu_821_w_tensor_2_12_V_re = {{wgt_mem_1_V_Dout_A[167:160]}};

assign grp_gemm_core_fu_821_w_tensor_2_13_V_re = {{wgt_mem_1_V_Dout_A[175:168]}};

assign grp_gemm_core_fu_821_w_tensor_2_14_V_re = {{wgt_mem_1_V_Dout_A[183:176]}};

assign grp_gemm_core_fu_821_w_tensor_2_15_V_re = {{wgt_mem_1_V_Dout_A[191:184]}};

assign grp_gemm_core_fu_821_w_tensor_2_1_V_rea = {{wgt_mem_0_V_Dout_A[143:136]}};

assign grp_gemm_core_fu_821_w_tensor_2_2_V_rea = {{wgt_mem_0_V_Dout_A[151:144]}};

assign grp_gemm_core_fu_821_w_tensor_2_3_V_rea = {{wgt_mem_0_V_Dout_A[159:152]}};

assign grp_gemm_core_fu_821_w_tensor_2_4_V_rea = {{wgt_mem_0_V_Dout_A[167:160]}};

assign grp_gemm_core_fu_821_w_tensor_2_5_V_rea = {{wgt_mem_0_V_Dout_A[175:168]}};

assign grp_gemm_core_fu_821_w_tensor_2_6_V_rea = {{wgt_mem_0_V_Dout_A[183:176]}};

assign grp_gemm_core_fu_821_w_tensor_2_7_V_rea = {{wgt_mem_0_V_Dout_A[191:184]}};

assign grp_gemm_core_fu_821_w_tensor_2_8_V_rea = {{wgt_mem_1_V_Dout_A[135:128]}};

assign grp_gemm_core_fu_821_w_tensor_2_9_V_rea = {{wgt_mem_1_V_Dout_A[143:136]}};

assign grp_gemm_core_fu_821_w_tensor_3_0_V_rea = {{wgt_mem_0_V_Dout_A[199:192]}};

assign grp_gemm_core_fu_821_w_tensor_3_10_V_re = {{wgt_mem_1_V_Dout_A[215:208]}};

assign grp_gemm_core_fu_821_w_tensor_3_11_V_re = {{wgt_mem_1_V_Dout_A[223:216]}};

assign grp_gemm_core_fu_821_w_tensor_3_12_V_re = {{wgt_mem_1_V_Dout_A[231:224]}};

assign grp_gemm_core_fu_821_w_tensor_3_13_V_re = {{wgt_mem_1_V_Dout_A[239:232]}};

assign grp_gemm_core_fu_821_w_tensor_3_14_V_re = {{wgt_mem_1_V_Dout_A[247:240]}};

assign grp_gemm_core_fu_821_w_tensor_3_15_V_re = {{wgt_mem_1_V_Dout_A[255:248]}};

assign grp_gemm_core_fu_821_w_tensor_3_1_V_rea = {{wgt_mem_0_V_Dout_A[207:200]}};

assign grp_gemm_core_fu_821_w_tensor_3_2_V_rea = {{wgt_mem_0_V_Dout_A[215:208]}};

assign grp_gemm_core_fu_821_w_tensor_3_3_V_rea = {{wgt_mem_0_V_Dout_A[223:216]}};

assign grp_gemm_core_fu_821_w_tensor_3_4_V_rea = {{wgt_mem_0_V_Dout_A[231:224]}};

assign grp_gemm_core_fu_821_w_tensor_3_5_V_rea = {{wgt_mem_0_V_Dout_A[239:232]}};

assign grp_gemm_core_fu_821_w_tensor_3_6_V_rea = {{wgt_mem_0_V_Dout_A[247:240]}};

assign grp_gemm_core_fu_821_w_tensor_3_7_V_rea = {{wgt_mem_0_V_Dout_A[255:248]}};

assign grp_gemm_core_fu_821_w_tensor_3_8_V_rea = {{wgt_mem_1_V_Dout_A[199:192]}};

assign grp_gemm_core_fu_821_w_tensor_3_9_V_rea = {{wgt_mem_1_V_Dout_A[207:200]}};

assign grp_gemm_core_fu_821_w_tensor_4_0_V_rea = {{wgt_mem_0_V_Dout_A[263:256]}};

assign grp_gemm_core_fu_821_w_tensor_4_10_V_re = {{wgt_mem_1_V_Dout_A[279:272]}};

assign grp_gemm_core_fu_821_w_tensor_4_11_V_re = {{wgt_mem_1_V_Dout_A[287:280]}};

assign grp_gemm_core_fu_821_w_tensor_4_12_V_re = {{wgt_mem_1_V_Dout_A[295:288]}};

assign grp_gemm_core_fu_821_w_tensor_4_13_V_re = {{wgt_mem_1_V_Dout_A[303:296]}};

assign grp_gemm_core_fu_821_w_tensor_4_14_V_re = {{wgt_mem_1_V_Dout_A[311:304]}};

assign grp_gemm_core_fu_821_w_tensor_4_15_V_re = {{wgt_mem_1_V_Dout_A[319:312]}};

assign grp_gemm_core_fu_821_w_tensor_4_1_V_rea = {{wgt_mem_0_V_Dout_A[271:264]}};

assign grp_gemm_core_fu_821_w_tensor_4_2_V_rea = {{wgt_mem_0_V_Dout_A[279:272]}};

assign grp_gemm_core_fu_821_w_tensor_4_3_V_rea = {{wgt_mem_0_V_Dout_A[287:280]}};

assign grp_gemm_core_fu_821_w_tensor_4_4_V_rea = {{wgt_mem_0_V_Dout_A[295:288]}};

assign grp_gemm_core_fu_821_w_tensor_4_5_V_rea = {{wgt_mem_0_V_Dout_A[303:296]}};

assign grp_gemm_core_fu_821_w_tensor_4_6_V_rea = {{wgt_mem_0_V_Dout_A[311:304]}};

assign grp_gemm_core_fu_821_w_tensor_4_7_V_rea = {{wgt_mem_0_V_Dout_A[319:312]}};

assign grp_gemm_core_fu_821_w_tensor_4_8_V_rea = {{wgt_mem_1_V_Dout_A[263:256]}};

assign grp_gemm_core_fu_821_w_tensor_4_9_V_rea = {{wgt_mem_1_V_Dout_A[271:264]}};

assign grp_gemm_core_fu_821_w_tensor_5_0_V_rea = {{wgt_mem_0_V_Dout_A[327:320]}};

assign grp_gemm_core_fu_821_w_tensor_5_10_V_re = {{wgt_mem_1_V_Dout_A[343:336]}};

assign grp_gemm_core_fu_821_w_tensor_5_11_V_re = {{wgt_mem_1_V_Dout_A[351:344]}};

assign grp_gemm_core_fu_821_w_tensor_5_12_V_re = {{wgt_mem_1_V_Dout_A[359:352]}};

assign grp_gemm_core_fu_821_w_tensor_5_13_V_re = {{wgt_mem_1_V_Dout_A[367:360]}};

assign grp_gemm_core_fu_821_w_tensor_5_14_V_re = {{wgt_mem_1_V_Dout_A[375:368]}};

assign grp_gemm_core_fu_821_w_tensor_5_15_V_re = {{wgt_mem_1_V_Dout_A[383:376]}};

assign grp_gemm_core_fu_821_w_tensor_5_1_V_rea = {{wgt_mem_0_V_Dout_A[335:328]}};

assign grp_gemm_core_fu_821_w_tensor_5_2_V_rea = {{wgt_mem_0_V_Dout_A[343:336]}};

assign grp_gemm_core_fu_821_w_tensor_5_3_V_rea = {{wgt_mem_0_V_Dout_A[351:344]}};

assign grp_gemm_core_fu_821_w_tensor_5_4_V_rea = {{wgt_mem_0_V_Dout_A[359:352]}};

assign grp_gemm_core_fu_821_w_tensor_5_5_V_rea = {{wgt_mem_0_V_Dout_A[367:360]}};

assign grp_gemm_core_fu_821_w_tensor_5_6_V_rea = {{wgt_mem_0_V_Dout_A[375:368]}};

assign grp_gemm_core_fu_821_w_tensor_5_7_V_rea = {{wgt_mem_0_V_Dout_A[383:376]}};

assign grp_gemm_core_fu_821_w_tensor_5_8_V_rea = {{wgt_mem_1_V_Dout_A[327:320]}};

assign grp_gemm_core_fu_821_w_tensor_5_9_V_rea = {{wgt_mem_1_V_Dout_A[335:328]}};

assign grp_gemm_core_fu_821_w_tensor_6_0_V_rea = {{wgt_mem_0_V_Dout_A[391:384]}};

assign grp_gemm_core_fu_821_w_tensor_6_10_V_re = {{wgt_mem_1_V_Dout_A[407:400]}};

assign grp_gemm_core_fu_821_w_tensor_6_11_V_re = {{wgt_mem_1_V_Dout_A[415:408]}};

assign grp_gemm_core_fu_821_w_tensor_6_12_V_re = {{wgt_mem_1_V_Dout_A[423:416]}};

assign grp_gemm_core_fu_821_w_tensor_6_13_V_re = {{wgt_mem_1_V_Dout_A[431:424]}};

assign grp_gemm_core_fu_821_w_tensor_6_14_V_re = {{wgt_mem_1_V_Dout_A[439:432]}};

assign grp_gemm_core_fu_821_w_tensor_6_15_V_re = {{wgt_mem_1_V_Dout_A[447:440]}};

assign grp_gemm_core_fu_821_w_tensor_6_1_V_rea = {{wgt_mem_0_V_Dout_A[399:392]}};

assign grp_gemm_core_fu_821_w_tensor_6_2_V_rea = {{wgt_mem_0_V_Dout_A[407:400]}};

assign grp_gemm_core_fu_821_w_tensor_6_3_V_rea = {{wgt_mem_0_V_Dout_A[415:408]}};

assign grp_gemm_core_fu_821_w_tensor_6_4_V_rea = {{wgt_mem_0_V_Dout_A[423:416]}};

assign grp_gemm_core_fu_821_w_tensor_6_5_V_rea = {{wgt_mem_0_V_Dout_A[431:424]}};

assign grp_gemm_core_fu_821_w_tensor_6_6_V_rea = {{wgt_mem_0_V_Dout_A[439:432]}};

assign grp_gemm_core_fu_821_w_tensor_6_7_V_rea = {{wgt_mem_0_V_Dout_A[447:440]}};

assign grp_gemm_core_fu_821_w_tensor_6_8_V_rea = {{wgt_mem_1_V_Dout_A[391:384]}};

assign grp_gemm_core_fu_821_w_tensor_6_9_V_rea = {{wgt_mem_1_V_Dout_A[399:392]}};

assign grp_gemm_core_fu_821_w_tensor_7_0_V_rea = {{wgt_mem_0_V_Dout_A[455:448]}};

assign grp_gemm_core_fu_821_w_tensor_7_10_V_re = {{wgt_mem_1_V_Dout_A[471:464]}};

assign grp_gemm_core_fu_821_w_tensor_7_11_V_re = {{wgt_mem_1_V_Dout_A[479:472]}};

assign grp_gemm_core_fu_821_w_tensor_7_12_V_re = {{wgt_mem_1_V_Dout_A[487:480]}};

assign grp_gemm_core_fu_821_w_tensor_7_13_V_re = {{wgt_mem_1_V_Dout_A[495:488]}};

assign grp_gemm_core_fu_821_w_tensor_7_14_V_re = {{wgt_mem_1_V_Dout_A[503:496]}};

assign grp_gemm_core_fu_821_w_tensor_7_15_V_re = {{wgt_mem_1_V_Dout_A[511:504]}};

assign grp_gemm_core_fu_821_w_tensor_7_1_V_rea = {{wgt_mem_0_V_Dout_A[463:456]}};

assign grp_gemm_core_fu_821_w_tensor_7_2_V_rea = {{wgt_mem_0_V_Dout_A[471:464]}};

assign grp_gemm_core_fu_821_w_tensor_7_3_V_rea = {{wgt_mem_0_V_Dout_A[479:472]}};

assign grp_gemm_core_fu_821_w_tensor_7_4_V_rea = {{wgt_mem_0_V_Dout_A[487:480]}};

assign grp_gemm_core_fu_821_w_tensor_7_5_V_rea = {{wgt_mem_0_V_Dout_A[495:488]}};

assign grp_gemm_core_fu_821_w_tensor_7_6_V_rea = {{wgt_mem_0_V_Dout_A[503:496]}};

assign grp_gemm_core_fu_821_w_tensor_7_7_V_rea = {{wgt_mem_0_V_Dout_A[511:504]}};

assign grp_gemm_core_fu_821_w_tensor_7_8_V_rea = {{wgt_mem_1_V_Dout_A[455:448]}};

assign grp_gemm_core_fu_821_w_tensor_7_9_V_rea = {{wgt_mem_1_V_Dout_A[463:456]}};

assign grp_gemm_core_fu_821_w_tensor_8_0_V_rea = {{wgt_mem_0_V_Dout_A[519:512]}};

assign grp_gemm_core_fu_821_w_tensor_8_10_V_re = {{wgt_mem_1_V_Dout_A[535:528]}};

assign grp_gemm_core_fu_821_w_tensor_8_11_V_re = {{wgt_mem_1_V_Dout_A[543:536]}};

assign grp_gemm_core_fu_821_w_tensor_8_12_V_re = {{wgt_mem_1_V_Dout_A[551:544]}};

assign grp_gemm_core_fu_821_w_tensor_8_13_V_re = {{wgt_mem_1_V_Dout_A[559:552]}};

assign grp_gemm_core_fu_821_w_tensor_8_14_V_re = {{wgt_mem_1_V_Dout_A[567:560]}};

assign grp_gemm_core_fu_821_w_tensor_8_15_V_re = {{wgt_mem_1_V_Dout_A[575:568]}};

assign grp_gemm_core_fu_821_w_tensor_8_1_V_rea = {{wgt_mem_0_V_Dout_A[527:520]}};

assign grp_gemm_core_fu_821_w_tensor_8_2_V_rea = {{wgt_mem_0_V_Dout_A[535:528]}};

assign grp_gemm_core_fu_821_w_tensor_8_3_V_rea = {{wgt_mem_0_V_Dout_A[543:536]}};

assign grp_gemm_core_fu_821_w_tensor_8_4_V_rea = {{wgt_mem_0_V_Dout_A[551:544]}};

assign grp_gemm_core_fu_821_w_tensor_8_5_V_rea = {{wgt_mem_0_V_Dout_A[559:552]}};

assign grp_gemm_core_fu_821_w_tensor_8_6_V_rea = {{wgt_mem_0_V_Dout_A[567:560]}};

assign grp_gemm_core_fu_821_w_tensor_8_7_V_rea = {{wgt_mem_0_V_Dout_A[575:568]}};

assign grp_gemm_core_fu_821_w_tensor_8_8_V_rea = {{wgt_mem_1_V_Dout_A[519:512]}};

assign grp_gemm_core_fu_821_w_tensor_8_9_V_rea = {{wgt_mem_1_V_Dout_A[527:520]}};

assign grp_gemm_core_fu_821_w_tensor_9_0_V_rea = {{wgt_mem_0_V_Dout_A[583:576]}};

assign grp_gemm_core_fu_821_w_tensor_9_10_V_re = {{wgt_mem_1_V_Dout_A[599:592]}};

assign grp_gemm_core_fu_821_w_tensor_9_11_V_re = {{wgt_mem_1_V_Dout_A[607:600]}};

assign grp_gemm_core_fu_821_w_tensor_9_12_V_re = {{wgt_mem_1_V_Dout_A[615:608]}};

assign grp_gemm_core_fu_821_w_tensor_9_13_V_re = {{wgt_mem_1_V_Dout_A[623:616]}};

assign grp_gemm_core_fu_821_w_tensor_9_14_V_re = {{wgt_mem_1_V_Dout_A[631:624]}};

assign grp_gemm_core_fu_821_w_tensor_9_15_V_re = {{wgt_mem_1_V_Dout_A[639:632]}};

assign grp_gemm_core_fu_821_w_tensor_9_1_V_rea = {{wgt_mem_0_V_Dout_A[591:584]}};

assign grp_gemm_core_fu_821_w_tensor_9_2_V_rea = {{wgt_mem_0_V_Dout_A[599:592]}};

assign grp_gemm_core_fu_821_w_tensor_9_3_V_rea = {{wgt_mem_0_V_Dout_A[607:600]}};

assign grp_gemm_core_fu_821_w_tensor_9_4_V_rea = {{wgt_mem_0_V_Dout_A[615:608]}};

assign grp_gemm_core_fu_821_w_tensor_9_5_V_rea = {{wgt_mem_0_V_Dout_A[623:616]}};

assign grp_gemm_core_fu_821_w_tensor_9_6_V_rea = {{wgt_mem_0_V_Dout_A[631:624]}};

assign grp_gemm_core_fu_821_w_tensor_9_7_V_rea = {{wgt_mem_0_V_Dout_A[639:632]}};

assign grp_gemm_core_fu_821_w_tensor_9_8_V_rea = {{wgt_mem_1_V_Dout_A[583:576]}};

assign grp_gemm_core_fu_821_w_tensor_9_9_V_rea = {{wgt_mem_1_V_Dout_A[591:584]}};

assign icmp_iter_out = ((iter_out_reg == inst_iter_out_reg) ? 1'b1 : 1'b0);  //

assign icmp_iter_in = ((iter_in_reg == inst_iter_in_reg) ? 1'b1 : 1'b0);

assign icmp_ln35_fu_1246_p2 = ((ap_phi_mux_upc_0_phi_fu_814_p4 < zext_ln35_reg_4785) ? 1'b1 : 1'b0);

assign inp_mem_V_Addr_A = inp_mem_V_Addr_A_orig << 32'd4;

assign inp_mem_V_Addr_A_orig = zext_ln544_1_fu_1316_p1;

assign inp_mem_V_Din_A = 128'd0;

assign inp_mem_V_WEN_A = 16'd0;

assign it_in_fu_1157_p2 = (iter_in_reg + 14'd1);

assign it_out_fu_1137_p2 = (iter_out_reg + 14'd1);

assign out_mem_V_Addr_A = out_mem_V_Addr_A_orig << 32'd4;

assign out_mem_V_Addr_A_orig = zext_ln544_2_reg_4829;

assign out_mem_V_Din_A = {{{{{{{{{{{{{{{{grp_gemm_core_fu_821_ap_return_31}, {grp_gemm_core_fu_821_ap_return_30}}, {grp_gemm_core_fu_821_ap_return_29}}, {grp_gemm_core_fu_821_ap_return_28}}, {grp_gemm_core_fu_821_ap_return_27}}, {grp_gemm_core_fu_821_ap_return_26}}, {grp_gemm_core_fu_821_ap_return_25}}, {grp_gemm_core_fu_821_ap_return_24}}, {grp_gemm_core_fu_821_ap_return_23}}, {grp_gemm_core_fu_821_ap_return_22}}, {grp_gemm_core_fu_821_ap_return_21}}, {grp_gemm_core_fu_821_ap_return_20}}, {grp_gemm_core_fu_821_ap_return_19}}, {grp_gemm_core_fu_821_ap_return_18}}, {grp_gemm_core_fu_821_ap_return_17}}, {grp_gemm_core_fu_821_ap_return_16}};

assign p_Result_10_fu_4697_p4 = {{insn_raw_V[107:97]}};

assign p_Result_11_fu_4716_p4 = {{insn_raw_V[127:118]}};

assign p_Result_1_fu_1208_p4 = {{insn_raw_V[96:86]}};

assign p_Result_4_fu_1163_p4 = {{insn_raw_V[20:8]}};

assign p_Result_5_fu_1227_p4 = {{insn_raw_V[117:108]}};

assign p_Result_6_fu_4678_p4 = {{insn_raw_V[85:75]}};

assign p_Result_7_fu_1270_p4 = {{uop_mem_V_2_q0[21:11]}};

assign p_Result_8_fu_1176_p4 = {{insn_raw_V[34:21]}};

assign p_Result_9_fu_1290_p4 = {{uop_mem_V_2_q0[31:22]}};

assign p_Result_s_fu_1189_p4 = {{insn_raw_V[74:64]}};

assign sext_ln35_fu_1251_p1 = ap_phi_mux_upc_0_phi_fu_814_p4;

assign src_idx_V_fu_1284_p2 = (zext_ln209_1_fu_1280_p1 + src_offset_in_0_reg_778);

assign src_offset_in_V_1_fu_4710_p2 = (zext_ln700_4_fu_4706_p1 + src_offset_in_0_reg_778);

assign src_offset_out_V_fu_1221_p2 = (zext_ln700_1_fu_1217_p1 + src_offset_in_V_reg_732);

assign trunc_ln647_fu_1256_p1 = uop_mem_V_2_q0[10:0];

assign uop_mem_V_2_address0 = sext_ln35_fu_1251_p1;

assign upc_1_fu_4470_p2 = ($signed(32'd1) + $signed(upc_0_reg_811));

assign upc_fu_1172_p1 = p_Result_4_fu_1163_p4;

assign wgt_idx_V_fu_1304_p2 = (zext_ln209_2_fu_1300_p1 + wgt_offset_in_0_reg_789);

assign wgt_mem_0_V_Addr_A = wgt_mem_0_V_Addr_A_orig << 32'd7;

assign wgt_mem_0_V_Addr_A_orig = zext_ln544_fu_1310_p1;

assign wgt_mem_0_V_Din_A = 1024'd0;

assign wgt_mem_0_V_WEN_A = 128'd0;

assign wgt_mem_1_V_Addr_A = wgt_mem_1_V_Addr_A_orig << 32'd7;

assign wgt_mem_1_V_Addr_A_orig = zext_ln544_fu_1310_p1;

assign wgt_mem_1_V_Din_A = 1024'd0;

assign wgt_mem_1_V_WEN_A = 128'd0;

assign wgt_offset_in_V_1_fu_4729_p2 = (zext_ln700_5_fu_4725_p1 + wgt_offset_in_0_reg_789);

assign wgt_offset_out_V_fu_1240_p2 = (zext_ln700_2_fu_1236_p1 + wgt_offset_in_V_reg_744);

assign zext_ln209_1_fu_1280_p1 = p_Result_7_fu_1270_p4;

assign zext_ln209_2_fu_1300_p1 = p_Result_9_fu_1290_p4;

assign zext_ln209_fu_1260_p1 = trunc_ln647_fu_1256_p1;

assign zext_ln35_fu_1185_p1 = p_Result_8_fu_1176_p4;

assign zext_ln544_1_fu_1316_p1 = src_idx_V_fu_1284_p2;

assign zext_ln544_2_fu_1321_p1 = dst_idx_V_fu_1264_p2;

assign zext_ln544_fu_1310_p1 = wgt_idx_V_fu_1304_p2;

assign zext_ln700_1_fu_1217_p1 = p_Result_1_fu_1208_p4;

assign zext_ln700_2_fu_1236_p1 = p_Result_5_fu_1227_p4;

assign zext_ln700_3_fu_4687_p1 = p_Result_6_fu_4678_p4;

assign zext_ln700_4_fu_4706_p1 = p_Result_10_fu_4697_p4;

assign zext_ln700_5_fu_4725_p1 = p_Result_11_fu_4716_p4;

assign zext_ln700_fu_1198_p1 = p_Result_s_fu_1189_p4;

always @ (posedge ap_clk) begin
    zext_ln35_reg_4785[31:14] <= 18'b000000000000000000;
    zext_ln544_2_reg_4829[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
end

endmodule //gemm
